<?php
$z[0]=Array("field","诺基亚,Android,四大理由",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","美国科技博客网站BusinessInsider今日发表署名托德·哈斯尔顿（Todd Haselton)的分析文章指出，如果诺基亚真的制定了应对Windows Phone失败的后备计划，那么Android平台无疑是最佳选择，原因是后者的生态系统更优，令诺基亚新品更具吸引力。",73,426);
$z[1][4]['name']="description";
$z[2]=Array("field","诺基亚选择Android四大理由：杀手级硬件团队",428,524);
$z[2][4]['name']="title";
$z[3]=Array("field","鹏哥哥",526,574);
$z[3][4]['name']="writer";
$z[4]=Array("field","安卓哥",576,624);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-7-3 15:11:19",626,683);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",685,722);
$z[6][4]['name']="body";
$z[7]=Array("field","",724,769);
$z[7][4]['name']="download_url";
$z[8]=Array("field","",771,810);
$z[8][4]['name']="app_id";
$z[9]=Array("field","",812,851);
$z[9][4]['name']="litpic";

?>