{dede:field name='keywords'}Google,Google Play,Android{/dede:field}
{dede:field name='description'}Google 在为开发者谋福利这方面做的还是可以的，之前有应用内购买、运营商帐单，现在又推出了应用内订阅。这就代表在原来的一次性购买之外，开发者们又多了一个每月捞钱的方法。比如说需要每月付费才会有新内容的游戏，或是年费、月费计划的服务、出版物。{/dede:field}
{dede:field name='title'}Google 为  Android 新增应用内订阅{/dede:field}
{dede:field name='writer'}鹏哥哥{/dede:field}
{dede:field name='source'}安卓哥{/dede:field}
{dede:field name='pubdate'}2012-5-27 15:29:11{/dede:field}
{dede:field name='body'}<a href='http://www.apkge.com/group/google' title='Google / 谷歌'><img src='/Article/uploads/allimg/c120706/13415613254c10-15A9.png' align='right' alt='Google / 谷歌'/></a>
                
                
	实话说 Google 在为开发者谋福利这方面做的还是可以的，之前有应用内购买、运营商帐单，现在又推出了应用内订阅。这就代表在原来的一次性购买之外，开发者们又多了一个每月捞钱的方法。比如说需要每月付费才会有新内容的游戏，或是年费、月费计划的服务、出版物。而对用户来说则可以轻松的在应用内完成订阅，而且通过一个特别的 publisher API 他们甚至可以在&nbsp;Google Play&nbsp;或其 Android 设备之外延长订阅。据了解，移动游戏公司 Glu Mobile 将抢先在他们的游戏「前线突击队」（Frontline Commando）中加入了订阅功能。我们相信未来还会有更多类似的产品出现，可能很快你就能在 Android 应用中订阅《纽约时报》或是购买 Spotify 高级帐号了。现在只要你的 Google Play 版本不低于 3.5 的话应该就可以看到应用内订阅功能了，有什么想买的就快点试试看吧。<a href="http://cn.engadget.com/2012/05/26/google-brings-in-app-subscriptions-to-android/"><img src="/attached/images/20120527/20120527152842_1406.jpg" style="border-top-width:1px;border-right-width:1px;border-bottom-width:1px;border-left-width:1px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px;margin-top:4px;margin-right:4px;margin-bottom:4px;margin-left:4px;" /></a>{/dede:field}
{dede:field name='download_url'}{/dede:field}
{dede:field name='app_id'}{/dede:field}
{dede:field name='litpic'}/Article/uploads/allimg/c120706/13415613254c10-15A9_lit.png{/dede:field}
