<?php
$z[0]=Array("field","三星,Galaxy S II,升级Androi",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","据报道，三星已经准备好了于10号开始的Galaxy S II升级Android 4.0的工作，从10号起，Galaxy S II的用户便可通过OTA或是连接三星kies的方式来进行升级。虽然此次三星并未透露Galaxy S II升级后的具体变化，但据称此次升级将提供Android 4.0所拥有的全部功能，包括新的多任务操作系统、人脸识别以及三星的TouchWiz用户",74,522);
$z[1][4]['name']="description";
$z[2]=Array("field","三星Galaxy S II今日升级Android 4.0",524,602);
$z[2][4]['name']="title";
$z[3]=Array("field","",604,643);
$z[3][4]['name']="writer";
$z[4]=Array("field","",645,684);
$z[4][4]['name']="source";
$z[5]=Array("field","",686,726);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",728,765);
$z[6][4]['name']="body";
$z[7]=Array("field","",767,812);
$z[7][4]['name']="download_url";
$z[8]=Array("field","",814,853);
$z[8][4]['name']="app_id";
$z[9]=Array("field","",855,894);
$z[9][4]['name']="litpic";

?>