<?php
$z[0]=Array("field","谷歌,应用开发商,谷歌钱包",0,76);
$z[0][4]['name']="keywords";
$z[1]=Array("field","北京时间3月12日消息，据国外媒体报道，谷歌日前表示，该公司旗下Google Play商店（原Android Market）的支付政策并未调整。消息人士上周透露，谷歌一直在施压应用和移动游戏开发者使用谷歌钱包（Google Wallet），希望仿效苹果iOS平台取得成功。",78,442);
$z[1][4]['name']="description";
$z[2]=Array("field","谷歌否认要求应用开发商使用谷歌钱包服务",444,539);
$z[2][4]['name']="title";
$z[3]=Array("field","",541,580);
$z[3][4]['name']="writer";
$z[4]=Array("field","",582,621);
$z[4][4]['name']="source";
$z[5]=Array("field","",623,663);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",665,702);
$z[6][4]['name']="body";
$z[7]=Array("field","",704,749);
$z[7][4]['name']="download_url";
$z[8]=Array("field","",751,790);
$z[8][4]['name']="app_id";
$z[9]=Array("field","",792,831);
$z[9][4]['name']="litpic";

?>