<field:softrank  islist="1" itemname="应用评分" type="int" isnull="true" default="3" rename="" function="GetRankStar(@me)" notsend="1"/>		
<field:softsize  itemname="应用大小" type="text" isnull="true" default="" rename="" />	
<field:softlinks  itemname="软件地址" type="softlinks" isnull="true" default="" rename="" />	
<field:introduce  itemname="详细介绍" type="htmltext" isnull="trnue" default="" rename="" />
<field:prcode itemname="二维码" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:prcode>
