<?php
$z[0]=Array("field","Google,计划用多平台“Goo",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","iOS 5的一大重要特性就是Siri助手，甚至有消息称Apple还将在Apple TV里集成Siri来通过语音控制并给你推荐好节目。Google也拥有出色的语音识别和数据挖掘能力，他们当然不会眼瞅着Siri变成人见人爱的个人助手，有消息称Google内部正在测试一个代号为Majel的Google助手。",74,465);
$z[1][4]['name']="description";
$z[2]=Array("field","Google 计划用多平台“Google 助手”跟 Siri 竞争上岗",467,570);
$z[2][4]['name']="title";
$z[3]=Array("field","",572,611);
$z[3][4]['name']="writer";
$z[4]=Array("field","",613,652);
$z[4][4]['name']="source";
$z[5]=Array("field","",654,694);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",696,733);
$z[6][4]['name']="body";
$z[7]=Array("field","",735,780);
$z[7][4]['name']="download_url";
$z[8]=Array("field","",782,821);
$z[8][4]['name']="app_id";
$z[9]=Array("field","",823,862);
$z[9][4]['name']="litpic";

?>