<?php
$z[0]=Array("field","LG将在2012年全面升级Andr",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","韩国手机制造商LG公司已经计划在2012年内为其智能手机产品升级安卓5.0操作系统。虽然目前谷歌公司还未正式公布安卓5.0操作系统，但事实上有很多手机制造商都已经开始着手规划基于该平台的新产品了。不过依照目前的形势看来，摆在手机厂商面前的首要问题便是如何尽快的提高手机的硬件配置水平以适",74,523);
$z[1][4]['name']="description";
$z[2]=Array("field","LG将在2012年全面升级Android 5.0",525,601);
$z[2][4]['name']="title";
$z[3]=Array("field","",603,642);
$z[3][4]['name']="writer";
$z[4]=Array("field","",644,683);
$z[4][4]['name']="source";
$z[5]=Array("field","",685,725);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",727,764);
$z[6][4]['name']="body";
$z[7]=Array("field","",766,811);
$z[7][4]['name']="download_url";
$z[8]=Array("field","",813,852);
$z[8][4]['name']="app_id";
$z[9]=Array("field","",854,893);
$z[9][4]['name']="litpic";

?>