<?php
$z[0]=Array("field","盛大手机,4.3寸双核",0,66);
$z[0][4]['name']="keywords";
$z[1]=Array("field","盛大前不久发布了手机操作系统乐众ROM，同时也有消息说要出手机。然而今天XDA智能手机网的关系网得来消息，盛大手机真的要来了！配置方面跟之前流传的有点相似，1GHz双核处理器，分辨率为960540屏的4.3寸屏幕，8G内存，乐众ROM的Andriod 4.0操作系统，但是售价为1199元，大家没看错，就是1199元！",68,503);
$z[1][4]['name']="description";
$z[2]=Array("field","传盛大手机为4.3寸双核 售价不是999元而是1199元",505,605);
$z[2][4]['name']="title";
$z[3]=Array("field","",607,646);
$z[3][4]['name']="writer";
$z[4]=Array("field","",648,687);
$z[4][4]['name']="source";
$z[5]=Array("field","",689,729);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",731,768);
$z[6][4]['name']="body";
$z[7]=Array("field","",770,815);
$z[7][4]['name']="download_url";
$z[8]=Array("field","",817,856);
$z[8][4]['name']="app_id";
$z[9]=Array("field","",858,897);
$z[9][4]['name']="litpic";

?>