<?php
$z[0]=Array("field","诺基亚CEO,改变决策",0,66);
$z[0][4]['name']="keywords";
$z[1]=Array("field","随着iOS平台和Android平台的兴起，众多老牌手机巨人的日子都变得不太好过。芬兰手机巨头诺基亚的境况可谓是风雨飘摇，塞班系统早已没落，而其孤注一掷的WP系统也前途未卜。近日，诺基亚CEO对公司近期所做的决定表示遗憾和后悔。",68,421);
$z[1][4]['name']="description";
$z[2]=Array("field","诺基亚CEO：假如时光能倒流将改变决策",423,512);
$z[2][4]['name']="title";
$z[3]=Array("field","鹏哥哥",514,562);
$z[3][4]['name']="writer";
$z[4]=Array("field","安卓哥",564,612);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-7-2 17:49:01",614,671);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",673,710);
$z[6][4]['name']="body";
$z[7]=Array("field","",712,757);
$z[7][4]['name']="download_url";
$z[8]=Array("field","",759,798);
$z[8][4]['name']="app_id";
$z[9]=Array("field","",800,839);
$z[9][4]['name']="litpic";

?>