<?php
$z[0]=Array("field","谷歌,Google Play,云存储",0,69);
$z[0][4]['name']="keywords";
$z[1]=Array("field","据国外媒体报道，Google 3月7日正式对外宣布推出Google Play，一个帮助用户发现、欣赏、分享数字娱乐内容的平台。Google Play基于云技术，让用户可以将自己的音乐、电影、电子书以及Android应用存储其中。",71,381);
$z[1][4]['name']="description";
$z[2]=Array("field","谷歌推Google Play 借云存储整合各数字平台",383,475);
$z[2][4]['name']="title";
$z[3]=Array("field","",477,516);
$z[3][4]['name']="writer";
$z[4]=Array("field","",518,557);
$z[4][4]['name']="source";
$z[5]=Array("field","",559,599);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",601,638);
$z[6][4]['name']="body";
$z[7]=Array("field","",640,685);
$z[7][4]['name']="download_url";
$z[8]=Array("field","",687,726);
$z[8][4]['name']="app_id";
$z[9]=Array("field","",728,767);
$z[9][4]['name']="litpic";

?>