<?php
$z[0]=Array("field","谷歌地图,地图服务收费",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","谷歌已开始对谷歌地图（Google Maps)等产品收费，并计划让这些产品自负盈亏。美国科技博客网站TechCrunch今日便撰文指出，谷歌的这种做法是一种短视行为，将不利于其长期发展。",74,353);
$z[1][4]['name']="description";
$z[2]=Array("field","谷歌对地图服务收费被指短视：不利长期发展",355,453);
$z[2][4]['name']="title";
$z[3]=Array("field","",455,494);
$z[3][4]['name']="writer";
$z[4]=Array("field","",496,535);
$z[4][4]['name']="source";
$z[5]=Array("field","",537,577);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",579,616);
$z[6][4]['name']="body";
$z[7]=Array("field","",618,663);
$z[7][4]['name']="download_url";
$z[8]=Array("field","",665,704);
$z[8][4]['name']="app_id";
$z[9]=Array("field","",706,745);
$z[9][4]['name']="litpic";

?>