{dede:field name='keywords'}小米2代手机,小米专利图{/dede:field}
{dede:field name='description'}近日有消息人士透露称，除了Android系统外，小米公司目前还在研发搭载WP8系统的第2代小米手机。该人还爆料称，除了研发WP8版小米2代手机外，他们还开始了基于WP8的MIUI V4系统的工作，预计小米的Android版手机也有可能同时搭载WP系统。{/dede:field}
{dede:field name='title'}小米2代手机专利图曝光 将搭载Android和WP8{/dede:field}
{dede:field name='writer'}鹏哥哥{/dede:field}
{dede:field name='source'}安卓哥{/dede:field}
{dede:field name='pubdate'}2012-7-3 17:12:03{/dede:field}
{dede:field name='body'}<a href='http://www.apkge.com/group/xiaomi' title='手机厂商 / xiaomi / 小米科技'><img src='/Article/uploads/allimg/c120706/1341561R43OP-2I126.gif' align='right' alt='手机厂商 / xiaomi / 小米科技'/></a>
                
                <p>
	近日有消息人士透露称，除了Android系统外，小米公司目前还在研发搭载WP8系统的第2代小米手机。该人还爆料称，除了研发WP8版小米2代手机外，他们还开始了基于WP8的MIUI V4系统的工作，预计小米的Android版手机也有可能同时搭载WP系统。
</p>
<p style="text-align:center;">
	<img src="http://www.apkge.com/attached/images/20120703/20120703171126_1406.jpg" border="0" width="500" alt="专利图已曝光 第二代小米手机瞄准WP8 " height="262" style="border-top-color:#333333;border-right-color:#333333;border-bottom-color:#333333;border-left-color:#333333;border-top-style:solid;border-right-style:solid;border-bottom-style:solid;border-left-style:solid;border-top-width:1px;border-right-width:1px;border-bottom-width:1px;border-left-width:1px;" /> 
</p>
<p style="text-align:center;">
	第二代小米手机
</p>
<p>
	此前雷军曾公开表示，小米手机将兼容Android和WP系统，并且与他还与微软商讨关于生产Windows Phone手机的相关事宜。分析人士表示，由于生产WP手机的厂商需要向微软提交授权费，WP版的小米手机可以会丢失廉价这个优势。
</p>{/dede:field}
{dede:field name='download_url'}{/dede:field}
{dede:field name='app_id'}{/dede:field}
{dede:field name='litpic'}/Article/uploads/allimg/c120706/1341561R43OP-2I126_lit.gif{/dede:field}
