<?php
$z[0]=Array("field","大屏双核,Android手机,摩托",0,74);
$z[0][4]['name']="keywords";
$z[1]=Array("field","摩托罗拉Droid RAZR（XT910）是摩托罗拉最新推出的一款机型，该机机身厚度仅有7.1毫米，非常纤薄。目前该机在经销商“星座科技”处最新报价为2999元，感兴趣的朋友可以关注一下。",76,358);
$z[1][4]['name']="description";
$z[2]=Array("field","大屏双核Android机 摩托罗拉RAZR超值价",360,446);
$z[2][4]['name']="title";
$z[3]=Array("field","",448,487);
$z[3][4]['name']="writer";
$z[4]=Array("field","",489,528);
$z[4][4]['name']="source";
$z[5]=Array("field","",530,570);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",572,609);
$z[6][4]['name']="body";
$z[7]=Array("field","",611,656);
$z[7][4]['name']="download_url";
$z[8]=Array("field","",658,697);
$z[8][4]['name']="app_id";
$z[9]=Array("field","",699,738);
$z[9][4]['name']="litpic";

?>