<?php
$z[0]=Array("field","",47,75);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",77,106);
$z[1][4]['name']="typename";
$z[2]=Array("field","",134,162);
$z[2][4]['name']="typeurl";
$z[3]=Array("arclist","\n\n				<div class=\"category_dis\">\n\n					<a href=\"[field:arcurl/]\" title=\"[field:title/]\" target=\"_blank\">[field:image/]</a><h4><a href=\"[field:arcurl/]\" target=\"_blank\" title=\"[field:title/]\">[field:title/]</a></h4><p>[field:info/]...</p>\n\n				</div>\n\n				",194,571);
$z[3][4]['row']="1";
$z[3][4]['orderby']="pubdate";
$z[3][4]['type']="image.";
$z[3][4]['imgwidth']="120";
$z[3][4]['imgheight']="95";
$z[3][4]['titlelen']="60";
$z[3][4]['infolen']="80";
$z[4]=Array("arclist","\n\n					<li><a href=\"[field:arcurl /]\" target=\"_blank\">[field:title /]</a></li>\n\n					",588,728);
$z[4][4]['titlelen']="60";
$z[4][4]['limit']="1,4";

?>