<?php
$z[0]=Array("field","Android 4.1,Flash Player,Nexus",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","Nexus 7这样高配低价的产品罕见异常，可以预见，消费者将非常欢乐。Nexus 7正炙手可热，在吸引无数人的眼球和口水的当下，Adobe带了一个坏消息：Flash Player支持Android 4.1的更新还为时尚早。",73,366);
$z[1][4]['name']="description";
$z[2]=Array("field","Android 4.1没有Flash Player还需要很长时间",368,456);
$z[2][4]['name']="title";
$z[3]=Array("field","鹏哥哥",458,506);
$z[3][4]['name']="writer";
$z[4]=Array("field","安卓哥",508,556);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-7-2 20:58:37",558,615);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",617,654);
$z[6][4]['name']="body";
$z[7]=Array("field","",656,701);
$z[7][4]['name']="download_url";
$z[8]=Array("field","",703,742);
$z[8][4]['name']="app_id";
$z[9]=Array("field","",744,783);
$z[9][4]['name']="litpic";

?>