<?php
$z[0]=Array("field","中国电信,千元智能机,上市",0,76);
$z[0][4]['name']="keywords";
$z[1]=Array("field","腾讯科技讯（孙实）3月10日消息，今日，有消息称，中国电信计划将推出iPhone 4S之外的其它类型手机，其中以千元智能手机为主，目前首批智能手机已经准备就绪。据了解，中国电信新引入的这批智能机价格将低于千元，操作系统仍是Android，屏幕达到4寸及4寸以上，有的机型可达4.3寸。",78,500);
$z[1][4]['name']="description";
$z[2]=Array("field","中国电信拟推千元智能机 首批上市手机已就绪",502,601);
$z[2][4]['name']="title";
$z[3]=Array("field","",603,642);
$z[3][4]['name']="writer";
$z[4]=Array("field","",644,683);
$z[4][4]['name']="source";
$z[5]=Array("field","",685,725);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",727,764);
$z[6][4]['name']="body";
$z[7]=Array("field","",766,811);
$z[7][4]['name']="download_url";
$z[8]=Array("field","",813,852);
$z[8][4]['name']="app_id";
$z[9]=Array("field","",854,893);
$z[9][4]['name']="litpic";

?>