
{dede:noteinfo notename="金毛介绍" channelid="1" macthtype="string"
	refurl="http://" sourcelang="gb2312" cosort="asc"
  isref="no" exptime="10" usemore="0" /}
{dede:listrule sourcetype="batch" rssurl="http://" regxurl="http://www.jinmao.org/jieshao/2_(*).html"
startid="2" endid="15" addv="1" urlrule="area" musthas=""
 nothas="" listpic="1" usemore="0"}
	{dede:addurls}http://www.jinmao.org/jieshao/{/dede:addurls}
	{dede:batchrule}{/dede:batchrule}
	{dede:regxrule}{/dede:regxrule}
	{dede:areastart}内容列表{/dede:areastart}
	{dede:areaend}<ul class="pagelist">
{/dede:areaend}
{/dede:listrule}

