<?php
$z[0]=Array("noteinfo","",2,163);
$z[0][4]['notename']="金毛介绍";
$z[0][4]['channelid']="1";
$z[0][4]['macthtype']="string";
$z[0][4]['refurl']="http://";
$z[0][4]['sourcelang']="gb2312";
$z[0][4]['cosort']="asc";
$z[0][4]['isref']="no";
$z[0][4]['exptime']="10";
$z[0][4]['usemore']="0";
$z[1]=Array("listrule","\r\n	{dede:addurls}http://www.jinmao.org/jieshao/{/dede:addurls}\r\n	{dede:batchrule}{/dede:batchrule}\r\n	{dede:regxrule}{/dede:regxrule}\r\n	{dede:areastart}内容列表{/dede:areastart}\r\n	{dede:areaend}<ul class=\"pagelist\">\r\n{/dede:areaend}\r\n",165,611);
$z[1][4]['sourcetype']="batch";
$z[1][4]['rssurl']="http://";
$z[1][4]['regxurl']="http://www.jinmao.org/jieshao/2_(*).html";
$z[1][4]['startid']="2";
$z[1][4]['endid']="15";
$z[1][4]['addv']="1";
$z[1][4]['urlrule']="area";
$z[1][4]['musthas']="";
$z[1][4]['nothas']="";
$z[1][4]['listpic']="1";
$z[1][4]['usemore']="0";

?>