<?php
$z[0]=Array("field","MIUI,第80周发布,更新日志",0,73);
$z[0][4]['name']="keywords";
$z[1]=Array("field","MIUI 2.3.9 已发布！ 本周MIUI 2.3开发版刷机推荐度：89%，查看详情1. 小米手机本周没有 2.3.5 稳定版，电信版目前暂不能刷MIUI 4.02. 小米手机2.3.5k及更高版本升级4.0刷机教程（注意：会清空用户数据），已是4.0版本的可以直接OTA升级3. Galaxy Nexus 今天启动内测；HTC Sensation G14、三星 I9100和华为 Honor今天有内测OTA",75,520);
$z[1][4]['name']="description";
$z[2]=Array("field","MIUI 2.3.9 第80周发布及更新日志",522,600);
$z[2][4]['name']="title";
$z[3]=Array("field","",602,641);
$z[3][4]['name']="writer";
$z[4]=Array("field","",643,682);
$z[4][4]['name']="source";
$z[5]=Array("field","",684,724);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",726,763);
$z[6][4]['name']="body";
$z[7]=Array("field","",765,810);
$z[7][4]['name']="download_url";
$z[8]=Array("field","",812,851);
$z[8][4]['name']="app_id";
$z[9]=Array("field","",853,892);
$z[9][4]['name']="litpic";

?>