<?php
$z[0]=Array("field","Android app泄私隐,被套信息",0,74);
$z[0][4]['name']="keywords";
$z[1]=Array("field","据香港《文汇报》3月5日报道，英国《星期日泰晤士报》利用软件追踪安卓（Android）手机下载智能手机用户下载程序（app）的数据传送，发现用户电话号码、电邮及位置等，最终会被传送至中国、印度、以色列及美国的公司。",76,417);
$z[1][4]['name']="description";
$z[2]=Array("field","英媒称Android app泄私隐 被套信息传遍美中印以",419,517);
$z[2][4]['name']="title";
$z[3]=Array("field","",519,558);
$z[3][4]['name']="writer";
$z[4]=Array("field","",560,599);
$z[4][4]['name']="source";
$z[5]=Array("field","",601,641);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",643,680);
$z[6][4]['name']="body";
$z[7]=Array("field","",682,727);
$z[7][4]['name']="download_url";
$z[8]=Array("field","",729,768);
$z[8][4]['name']="app_id";
$z[9]=Array("field","",770,809);
$z[9][4]['name']="litpic";

?>