<div class="g">

				<h2><span>分类：<a href="[field:typeurl/]" target="_blank">[[field:typename/]]</a></span><a href="[field:arcurl/]" target="_blank" title="[field:title  function='html2text(@me)' /]">[field:title function="cn_substr(Html2text(@me),75)" /]</a><em class="list_time">[field:stime/]</em></h2>

				<p>[field:array runphp='yes']@me = (strpos(@me['litpic'],'defaultpic') ? "" : "<a href='{@me['arcurl']}' class='imgview' target='_blank'><img src='{dede:global.cfg_basehost/}{@me['litpic']}' align='right' alt='{@me['title']}' width='100' height='100'/></a>"); [/field:array] [field:description  function="cn_substr(Html2text(@me),300)"/]... <a href="[field:arcurl/]" target="_blank">阅读全文&gt;&gt;</a> <span class="data"><em class="list_view">[field:click/]围观</em><em class="list_tag">标签：[field:id function=GetTags(@me)/] 

		   </em></span> </p>

			</div>