<?php
$z[0]=Array("field","Android,原生浏览器,手机浏",0,74);
$z[0][4]['name']="keywords";
$z[1]=Array("field","前些天我们刚刚报道过PC机最新浏览器。然而手机端浏览器也变得越来越重要。有一个来自StatCounter的新报道称在手机领域内，Google Android浏览器在全球最受欢迎。这个图表显示的是自2012年2月以来，Android浏览器的用户在全球占据22.67%，紧随其后的是占据21.7%的Opera。",76,469);
$z[1][4]['name']="description";
$z[2]=Array("field","Android原生浏览器成为最受欢迎的手机浏览器",471,567);
$z[2][4]['name']="title";
$z[3]=Array("field","",569,608);
$z[3][4]['name']="writer";
$z[4]=Array("field","",610,649);
$z[4][4]['name']="source";
$z[5]=Array("field","",651,691);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",693,730);
$z[6][4]['name']="body";
$z[7]=Array("field","",732,777);
$z[7][4]['name']="download_url";
$z[8]=Array("field","",779,818);
$z[8][4]['name']="app_id";
$z[9]=Array("field","",820,859);
$z[9][4]['name']="litpic";

?>