<?php
$z[0]=Array("field","电信,手机UI界面,天翼桌面",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","近期，记者发现中国电信方面已经开始为用户提供自主UI界面应用的下载，该桌面中还配合以各类云服务功能，用户安装后便可使用相应的天翼云手机服务。目前在Android手机系统环境中已经有众多第三方桌面来配合用户使用，其中很多UI可以允许用户在不必刷机的情况下，便可更换 Android手机中的桌面UI进行",77,526);
$z[1][4]['name']="description";
$z[2]=Array("field","电信推自主手机UI界面天翼桌面 提供手机云服务",528,629);
$z[2][4]['name']="title";
$z[3]=Array("field","",631,670);
$z[3][4]['name']="writer";
$z[4]=Array("field","",672,711);
$z[4][4]['name']="source";
$z[5]=Array("field","",713,753);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",755,792);
$z[6][4]['name']="body";
$z[7]=Array("field","",794,839);
$z[7][4]['name']="download_url";
$z[8]=Array("field","",841,880);
$z[8][4]['name']="app_id";
$z[9]=Array("field","",882,921);
$z[9][4]['name']="litpic";

?>