<?php
$z[0]=Array("top","\n  <m:item name='插件管理器' link='plus_main.php' rank='10' target='main' />\n  <m:item name='挑错管理' link='erraddsave.php' rank='plus_挑错管理' target='main' />\r\n<m:item name='百度新闻' link='baidunews.php' rank='plus_百度新闻' target='main' />\r\n<m:item name='文件管理器' link='file_manage_main.php' rank='plus_文件管理器' target='main' />\r\n<m:item name='广告管理' link='ad_main.php' rank='plus_广告管理' target='main' />\r\n<m:item name='友情链接' link='friendlink_main.php' rank='plus_友情链接模块' target='main' />\r\n<m:item name='投票模块' link='vote_main.php' rank='plus_投票模块' target='main' />\r\n<m:item name='bShare分享插件' link='plus_bshare.php' rank='plus_bShare分享插件' target='main' />\r\n<m:item name='留言簿模块' link='catalog_do.php?dopost=guestbook' rank='plus_留言簿模块' target='main' />\r\n\n",50,993);
$z[0][4]['item']="7";
$z[0][4]['name']="辅助插件";
$z[0][4]['display']="block";
$z[1]=Array("top","\r\n<m:item name='基本设置' link='cjx.php?ac=setting' rank='' target='main' />\r\n<m:item name='高级设置' link='cjx.php?ac=advanced' rank='' target='main' />\r\n<m:item name='伪原创设置' link='cjx.php?ac=seo' rank='' target='main' />\r\n<m:item name='搜索优化设置' link='cjx.php?ac=search' rank='' target='main' />\r\n<m:item name='采集任务' link='cjx.php?ac=task' rank='' target='main' />\r\n<m:item name='在线更新' link='cjx.php?ac=update' rank='' target='main' />\r\n<m:item name='我的授权' link='cjx.php?ac=mykey' rank='' target='main' />\r\n<m:item name='会员系统' link='cjx.php?ac=credits' rank='' target='main' />\r\n<m:item name='帮助中心' link='http://www.dedeapps.com/Related/?plugin=caijixia' rank='' target='main' />\r\n",995,1809);
$z[1][4]['name']="采集侠";
$z[1][4]['c']="1,";
$z[1][4]['display']="block";
$z[1][4]['rank']="";

?>