{dede:field name='keywords'}游戏开发商,Battleheart,And{/dede:field}
{dede:field name='description'}Battleheart是一款同时登陆iOS 和 Android 的掌上游戏，其画风精巧新颖，人物造型可爱，可玩性非常强。然而就在 3 月 9 日，Battleheart 的开发小组 MikaMobile 在其博客上宣布将放弃对其 Android 版本的继续支持，在这篇博客中，Mika Mobile 罗列了Android Market （已更名为 Google Play ）的诸多不是。它指责 Android Market 一方{/dede:field}
{dede:field name='title'}为何游戏开发商Battleheart 放弃 Android 版本说起{/dede:field}
{dede:field name='writer'}鹏哥哥{/dede:field}
{dede:field name='source'}安卓哥{/dede:field}
{dede:field name='pubdate'}2012-3-19 10:49:39{/dede:field}
{dede:field name='body'}<a href='http://www.apkge.com/group/Android' title='Android'><img src='/Article/uploads/allimg/c120706/13415615314RZ-1G314.gif' align='right' alt='Android'/></a>
                
                


	<p style="text-align:center;">
		<br />
	</p>
	<p align="center">
		<img alt="" src="/Article/uploads/allimg/c120706/13415C114364Z-41c9.jpg" /> 
	</p>
	<p>
		<br />
	</p>
	<p style="padding-right:0px;padding-left:0px;padding-bottom:0px;margin:0px 0px 20px;word-spacing:0px;font:14px/22px arial， helvetica， ’Hiragino Sans GB’， ’WenQuanYi Micro Hei’， sans-serif;text-transform:none;color:#333333;text-indent:2em;padding-top:0px;white-space:normal;letter-spacing:normal;background-color:#ffffff;text-align:left;-webkit-text-size-adjust:auto;-webkit-text-stroke-width:0px;widows:2;orphans:2;">
		Battleheart是一款同时登陆iOS 和 Android 的掌上游戏，其画风精巧新颖，人物造型可爱，可玩性非常强。然而就在 3 月 9 日，Battleheart 的开发小组<span class="Apple-converted-space"> </span>MikaMobile<span class="Apple-converted-space"> </span>在其博客上宣布将放弃对其 Android 版本的继续支持，在这篇博客中，Mika Mobile 罗列了Android Market （已更名为 Google Play ）的诸多不是。它指责 Android Market 一方面限制 App 大小，一方面却又允许开发者提供额外的数据包供用户下载，另外 Android Market 在下载 App 时，要求设备必须保证 30M ~ 50M 的下载缓存，而许多机型并没有足够的内存来满足这样的要求。尽管后续版本的 Android 允许用户将 Apps 安装在 SD 卡上，但作者表示已经无力再修改 App 以使其适用新版本系统的要求了。
	</p>
	<p style="padding-right:0px;padding-left:0px;padding-bottom:0px;margin:0px 0px 20px;word-spacing:0px;font:14px/22px arial， helvetica， ’Hiragino Sans GB’， ’WenQuanYi Micro Hei’， sans-serif;text-transform:none;color:#333333;text-indent:2em;padding-top:0px;white-space:normal;letter-spacing:normal;background-color:#ffffff;text-align:left;-webkit-text-size-adjust:auto;-webkit-text-stroke-width:0px;widows:2;orphans:2;">
		而当谈及在 Android 平台的开支和收益时，Mika Mobile 更是满腹怨言，它说：
	</p>
	<blockquote style="padding-right:5px;padding-left:10px;padding-bottom:1px;margin:15px 10px 0.75em;word-spacing:0px;font:14px/22px arial， helvetica， ’Hiragino Sans GB’， ’WenQuanYi Micro Hei’， sans-serif;text-transform:none;color:#333333;text-indent:0px;padding-top:7px;white-space:normal;letter-spacing:normal;background-color:#ffffff;text-align:left;-webkit-text-size-adjust:auto;-webkit-text-stroke-width:0px;widows:2;orphans:2;">
		<p style="padding-right:0px;padding-left:0px;padding-bottom:0px;margin:0px 0px 8px;padding-top:0px;">
			去年，我们花费了约 20％ 的总人工时间来处理 Android 版本出现的这样或那样的问题 —— 移植、平台特定的 bug 修复，客户服务等等。我更愿意把时间花在为你们提供更多的内容上，而不是吃力不讨好地修改着色和纹理格式以适应不同的 GPU ，或者推出新的补丁以使其支持新的设备而不会发生崩溃，又或者请教他人怎样修复一个没能通过审查的安装包<span style="color:#000000;">。</span>我们花费了不菲的开支用于测试各式各样的硬件。这些都是我们开发 Android 版本的必走流程。与此同时，Android 版本的销售总额仅为我们年收入的 5％ 左右，并且还持续萎缩。不用说，（即便是）这个比例也是难以维持的。
		</p>
	</blockquote>
	<p style="padding-right:0px;padding-left:0px;padding-bottom:0px;margin:0px 0px 20px;word-spacing:0px;font:14px/22px arial， helvetica， ’Hiragino Sans GB’， ’WenQuanYi Micro Hei’， sans-serif;text-transform:none;color:#333333;text-indent:2em;padding-top:0px;white-space:normal;letter-spacing:normal;background-color:#ffffff;text-align:left;-webkit-text-size-adjust:auto;-webkit-text-stroke-width:0px;widows:2;orphans:2;">
		<span id="more-78784"></span>
	</p>
	<p style="text-indent:2em;">
		而在 3 月 11 日，据 The Verge<span class="Apple-converted-space"> </span>报道，在 iOS 平台备受赞誉的免费拍照分享工具 Instagram 宣布不久后将登陆 Android 平台。在 SXSW 会展上，Instagram 的创始人 Kevin Systrom 向人们展示了运行在 Galaxy Nexus 上的 Instagram 应用，同时补充道：
	</p>
	<blockquote style="padding-right:5px;padding-left:10px;padding-bottom:1px;margin:15px 10px 0.75em;word-spacing:0px;font:14px/22px arial， helvetica， ’Hiragino Sans GB’， ’WenQuanYi Micro Hei’， sans-serif;text-transform:none;color:#333333;text-indent:0px;padding-top:7px;white-space:normal;letter-spacing:normal;background-color:#ffffff;text-align:left;-webkit-text-size-adjust:auto;-webkit-text-stroke-width:0px;widows:2;orphans:2;">
		<p style="padding-right:0px;padding-left:0px;padding-bottom:0px;margin:0px 0px 8px;padding-top:0px;">
			它将是你见过的最出色的 Android 应用之一，某种程度上，甚至比它的 <!--keyword--><span class="infoDataBank">iPhone<!--keyword-->
			
				
					
					
				
				
				
				
				
			
</span><!--/keyword-->版本更优秀。
			<p>
				<br />
			</p>
				</blockquote>
				<p style="padding-right:0px;padding-left:0px;padding-bottom:0px;margin:0px 0px 20px;word-spacing:0px;font:14px/22px arial， helvetica， ’Hiragino Sans GB’， ’WenQuanYi Micro Hei’， sans-serif;text-transform:none;color:#333333;text-indent:2em;padding-top:0px;white-space:normal;letter-spacing:normal;background-color:#ffffff;text-align:left;-webkit-text-size-adjust:auto;-webkit-text-stroke-width:0px;widows:2;orphans:2;">
					Battleheart 和 Instagram 对 Android 截然相反的两种看法有点令人费解，不过仔细分析后不难发现，这两款应用最大的区别在于 Battleheart 是一款售价为 2.99 美元的收费应用，而 Instagram 则完全免费，似乎正是这点区别决定了二者对 Android 平台天壤之别的态度。如果真是价格问题，那通过这件事，我们再次看到 Android 平台存在已久的问题，那就是：
				</p>
				<blockquote style="padding-right:5px;padding-left:10px;padding-bottom:1px;margin:15px 10px 0.75em;word-spacing:0px;font:14px/22px arial， helvetica， ’Hiragino Sans GB’， ’WenQuanYi Micro Hei’， sans-serif;text-transform:none;color:#333333;text-indent:0px;padding-top:7px;white-space:normal;letter-spacing:normal;background-color:#ffffff;text-align:left;-webkit-text-size-adjust:auto;-webkit-text-stroke-width:0px;widows:2;orphans:2;">
					<p style="padding-right:0px;padding-left:0px;padding-bottom:0px;margin:0px 0px 8px;padding-top:0px;">
						开发 Android 收费应用似乎真的不赚钱。
					</p>
				</blockquote>
				<p style="padding-right:0px;padding-left:0px;padding-bottom:0px;margin:0px 0px 20px;word-spacing:0px;font:14px/22px arial， helvetica， ’Hiragino Sans GB’， ’WenQuanYi Micro Hei’， sans-serif;text-transform:none;color:#333333;text-indent:2em;padding-top:0px;white-space:normal;letter-spacing:normal;background-color:#ffffff;text-align:left;-webkit-text-size-adjust:auto;-webkit-text-stroke-width:0px;widows:2;orphans:2;">
					类似的开发商对 Android 的抱怨我们早有耳闻，而就在前两天，仍然有开发者抱怨<span class="Apple-converted-space"> </span>Google 支付费用过于迟缓。与苹果的 App Store 相比，Android Market 更像一个 Free Market ，其主页上向用户推介的也几乎都是免费应用。牛津大学在 3 月 6 日发布的调查报道中称：
				</p>
				<blockquote style="padding-right:5px;padding-left:10px;padding-bottom:1px;margin:15px 10px 0.75em;word-spacing:0px;font:14px/22px arial， helvetica， ’Hiragino Sans GB’， ’WenQuanYi Micro Hei’， sans-serif;text-transform:none;color:#333333;text-indent:0px;padding-top:7px;white-space:normal;letter-spacing:normal;background-color:#ffffff;text-align:left;-webkit-text-size-adjust:auto;-webkit-text-stroke-width:0px;widows:2;orphans:2;">
					<p style="padding-right:0px;padding-left:0px;padding-bottom:0px;margin:0px 0px 8px;padding-top:0px;">
						Android Market 包含了免费应用的大部分（73%）。有分析指出这些应用中大约有 80% 依靠针对性的广告支撑。此外，就付费应用而言，免费应用更受欢迎：在付费软件中，下载量超过 100 次的约为 20% ，超过 10000 次的仅为 0.2% （相比较下，免费应用对应的数字为 20% ）。
					</p>
				</blockquote>
				<p style="padding-right:0px;padding-left:0px;padding-bottom:0px;margin:0px 0px 20px;word-spacing:0px;font:14px/22px arial， helvetica， ’Hiragino Sans GB’， ’WenQuanYi Micro Hei’， sans-serif;text-transform:none;color:#333333;text-indent:2em;padding-top:0px;white-space:normal;letter-spacing:normal;background-color:#ffffff;text-align:left;-webkit-text-size-adjust:auto;-webkit-text-stroke-width:0px;widows:2;orphans:2;">
					细想之下，这与 Android 自身的气质极为吻合。Android 本来就是一款免费系统，以免费、开放为主要特点来吸引设备商和开发者。这种前提下，Battleheart 和 Instagram 对 Android 天差地别的态度就不难理解了：
				</p>
				<p style="padding-right:0px;padding-left:0px;padding-bottom:0px;margin:0px 0px 20px;word-spacing:0px;font:14px/22px arial， helvetica， ’Hiragino Sans GB’， ’WenQuanYi Micro Hei’， sans-serif;text-transform:none;color:#333333;text-indent:2em;padding-top:0px;white-space:normal;letter-spacing:normal;background-color:#ffffff;text-align:left;-webkit-text-size-adjust:auto;-webkit-text-stroke-width:0px;widows:2;orphans:2;">
					Instagram作为一款基于社交网络的应用，在 Android 平台发布免费的 App ，能够迅速地聚揽大量用户，后期可以通过广告服务来获取效益。相比之下，Battleheart 作为一款以本地内容为主的掌上游戏，在获益手段上远没有 Instagram 丰富，其主要的收入只能来源于用户的付费下载。而 Android Market 推崇的免费策略让付费应用在这样的平台里显得格格不入，下载量得不到保证，收入自然就无从谈起。再加上因 Android 平台分裂带来的兼容性问题、不同设备间的运行调试，以及日常的管理维护，开发者的工作量在无形中增加了许多，这将使新版本的开发工作难以为继。这么分析的话，Battleheart 放弃对 Android 版本的继续开发就合乎情理了。
				</p>
				<p style="padding-right:0px;padding-left:0px;padding-bottom:0px;margin:0px 0px 20px;word-spacing:0px;font:14px/22px arial， helvetica， ’Hiragino Sans GB’， ’WenQuanYi Micro Hei’， sans-serif;text-transform:none;color:#333333;text-indent:2em;padding-top:0px;white-space:normal;letter-spacing:normal;background-color:#ffffff;text-align:left;-webkit-text-size-adjust:auto;-webkit-text-stroke-width:0px;widows:2;orphans:2;">
					想当初，Google 推崇的免费、开放策略为 Android 赢来了大批的设备商、开发者和用户，这也让 Android 在众多 iOS 竞争者中崭露头角。然而时至今日，也正是免费和开放，造成了 Android 设备商各自为政、平台分裂的局面。由此带来的应用在不同设备和系统版本间的不兼容性，更是让开发者们疲于应对——只是不希望 Battleheart 造成一种恐慌气氛。
				</p>{/dede:field}
{dede:field name='download_url'}{/dede:field}
{dede:field name='app_id'}{/dede:field}
{dede:field name='litpic'}/Article/uploads/allimg/c120706/13415615314RZ-1G314_lit.gif{/dede:field}
