<?php
$z[0]=Array("field","卡巴斯基Android版,腾讯合作",0,76);
$z[0][4]['name']="keywords";
$z[1]=Array("field","DoNews 3月9日消息 卡巴斯基与腾讯无线事业部日前在手机病毒样本分析领域达成合作，同时腾讯将作为卡巴斯基手机安全软件（KMS9）中文Android版互联网首发合作伙伴，用户在腾讯应用中心下载，可享受6个月的免费服务。",78,411);
$z[1][4]['name']="description";
$z[2]=Array("field","卡巴斯基Android版杀软与腾讯合作 6个月免费使用",413,514);
$z[2][4]['name']="title";
$z[3]=Array("field","",516,555);
$z[3][4]['name']="writer";
$z[4]=Array("field","",557,596);
$z[4][4]['name']="source";
$z[5]=Array("field","",598,638);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",640,677);
$z[6][4]['name']="body";
$z[7]=Array("field","",679,724);
$z[7][4]['name']="download_url";
$z[8]=Array("field","",726,765);
$z[8][4]['name']="app_id";
$z[9]=Array("field","",767,806);
$z[9][4]['name']="litpic";

?>