<?php
$z[0]=Array("field","CM9,三星Galaxy Tab 10.1,华硕",0,73);
$z[0][4]['name']="keywords";
$z[1]=Array("field","CyanogenMod团队一直在努力开发CyanogenMod 9 Nightlies Build，近日，又新增了三星平板电脑Galaxy Tab 10.1和华硕平板电脑Transformer TF101、Transformer Prime TF201。不过要注意的是，Nightlies Build是由Server自行编译，并非正式版，虽然经过测试，不过还是可能存在问题。除了这三款平板电脑，摩托罗拉的Xoom wifi版在之前也得到",75,523);
$z[1][4]['name']="description";
$z[2]=Array("field","CM9新增三星Galaxy Tab 10.1和华硕Transformer TF101、TF201",525,627);
$z[2][4]['name']="title";
$z[3]=Array("field","",629,668);
$z[3][4]['name']="writer";
$z[4]=Array("field","",670,709);
$z[4][4]['name']="source";
$z[5]=Array("field","",711,751);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",753,790);
$z[6][4]['name']="body";
$z[7]=Array("field","",792,837);
$z[7][4]['name']="download_url";
$z[8]=Array("field","",839,878);
$z[8][4]['name']="app_id";
$z[9]=Array("field","",880,919);
$z[9][4]['name']="litpic";

?>