<?php
$z[0]=Array("field","Android 4.0系统,三星i9250,售",0,74);
$z[0][4]['name']="keywords";
$z[1]=Array("field","这款三星i9250以首款搭载了Android4.0 系统手机的身份以及自身强悍的配置吸引了无数关注。同时GALAXY Nexus支持NFC、蓝牙3.0技术，并且加入了3G、LTE网络的支持，在目前的智能手机市场算得上是顶级旗舰产品，今天笔者从睿风电讯得到消息，该机仅售2899元，喜欢的朋友可多关注一下。",76,490);
$z[1][4]['name']="description";
$z[2]=Array("field","原生Android 4.0系统 三星i9250售价2899元",492,578);
$z[2][4]['name']="title";
$z[3]=Array("field","",580,619);
$z[3][4]['name']="writer";
$z[4]=Array("field","",621,660);
$z[4][4]['name']="source";
$z[5]=Array("field","",662,702);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",704,741);
$z[6][4]['name']="body";
$z[7]=Array("field","",743,788);
$z[7][4]['name']="download_url";
$z[8]=Array("field","",790,829);
$z[8][4]['name']="app_id";
$z[9]=Array("field","",831,870);
$z[9][4]['name']="litpic";

?>