<?php
$z[0]=Array("field","Android下一代,Key Lime Pie",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","我们知道Android 5.0的开发代号将会被称为“Jelly Bean”，这是一种孩子们很喜欢的果汁软糖豆，而再往后推我们还可以发现一个新的名字，那就叫Key Lime Pie，这是一种青柠风味的蛋糕甜点，很能勾起人的食欲，这套系统有可能会在2013年左右发布，但我们至今没有任何消息可以提供，只有上一幅点心的图解解",72,519);
$z[1][4]['name']="description";
$z[2]=Array("field","Android下一代将被命名为Key Lime Pie",521,602);
$z[2][4]['name']="title";
$z[3]=Array("field","",604,643);
$z[3][4]['name']="writer";
$z[4]=Array("field","",645,684);
$z[4][4]['name']="source";
$z[5]=Array("field","",686,726);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",728,765);
$z[6][4]['name']="body";
$z[7]=Array("field","",767,812);
$z[7][4]['name']="download_url";
$z[8]=Array("field","",814,853);
$z[8][4]['name']="app_id";
$z[9]=Array("field","",855,894);
$z[9][4]['name']="litpic";

?>