<?php
$z[0]=Array("field","讯飞语音输入法,",0,63);
$z[0][4]['name']="keywords";
$z[1]=Array("field","2012年3月9日，安徽科大讯飞信息科技股份有限公司发布了讯飞语音输入法（Android）v2.1.1130 beta版。新版在键盘输入上新增对简拼输入联系人姓名功能的全面支持，只要通过词库管理导入联系人词库，就可以方便地输入联系人。另外在手写输入上，增加了对部分特殊符号（如‰ € ℃♀ ♂等）的手写识别支持",65,514);
$z[1][4]['name']="description";
$z[2]=Array("field","讯飞语音输入法v2.1.1130发布：导入联系人词库 输入更方便",516,630);
$z[2][4]['name']="title";
$z[3]=Array("field","",632,671);
$z[3][4]['name']="writer";
$z[4]=Array("field","",673,712);
$z[4][4]['name']="source";
$z[5]=Array("field","",714,754);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",756,793);
$z[6][4]['name']="body";
$z[7]=Array("field","",795,840);
$z[7][4]['name']="download_url";
$z[8]=Array("field","",842,881);
$z[8][4]['name']="app_id";
$z[9]=Array("field","",883,922);
$z[9][4]['name']="litpic";

?>