{dede:field name='keywords'}微软工程师,Android设备,僵{/dede:field}
{dede:field name='description'}据国外媒体报道，杀毒软件厂商趋势科技称，针对Android的恶意软件数量正在以惊人的速度增长。另外，微软一位反垃圾邮件工程师也发现了一个控制Android设备的跨国僵尸网络。{/dede:field}
{dede:field name='title'}微软工程师发现Android设备被僵尸网络控制{/dede:field}
{dede:field name='writer'}鹏哥哥{/dede:field}
{dede:field name='source'}安卓哥{/dede:field}
{dede:field name='pubdate'}2012-7-5 22:09:59{/dede:field}
{dede:field name='body'}<p>
	据国外媒体报道，杀毒软件厂商趋势科技称，针对Android的恶意软件数量正在以惊人的速度增长。另外，微软一位反垃圾邮件工程师也发现了一个控制Android设备的跨国僵尸网络。
</p>

	<img alt="微软发现Android设备被僵尸网络控制" src="http://www.apkge.com/attached/images/20120705/20120705220909_7968.jpg" /> 

<p style="text-align:center;">
	<br />
</p>
<p style="text-align:center;">
	微软发现Android设备被僵尸网络控制（腾讯科技配图）
</p>
<p>
	趋势科技称，瞄准谷歌(微博)Android移动操作系统的恶意应用程序数量已从年初的超过5000个，上升到近几个月的2万个。到第三季度估计发现的恶意软件样本将达到3.8万个左右，到第四季度将接近13万个。
</p>
<p>
	谷歌的Google Play成为被利用来发布恶意的窃取数据或侵犯隐私应用程序的平台，可以说是很多恶意应用程序的发源地。趋势科技称，在谷歌删除前，有10多个恶意应用程序被下载了超过70万次。被发现的恶意软件样本各种各样，有些是窃取数据，有些是通过GPS跟踪设备，另外一些是发布广告或安装自动拨号器拨打收费电话。
</p>
<p>
	而微软反垃圾邮件工程师特里·辛克（Terry Zink）制MSDN博客上称，他分析了一些标题包含“发自Android雅虎电邮”的垃圾邮件样本，发现这些邮件都是来自中东、亚洲和东欧的一些地点。他表示：“我敢打赌，这些手机用户下载了一些恶意应用程序，不愿购买合法版本，但他们的损失超过了购买合法版本的费用。或者他们用了一种流氓雅虎电邮。”
</p>
<p>
	这不是首次发现Android恶意软件与僵尸网络有关，早在今年2月研究人员就发现一种恶意应用程序感染了大多数运行Gingerbread系统的中国用户设备，该软件可获得根访问权并拨打收费电话为制作者牟利。
</p>
                <span id="Lb_laiyuan" class="hs"><br/>来源：<strong>腾讯科技</strong></span>{/dede:field}
{dede:field name='download_url'}{/dede:field}
{dede:field name='app_id'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
