<?php
$z[0]=Array("field","Android设备,日激活量85万台",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","据国外媒体报道，Android保持强劲势头，每天保持85万部Android系统的电话与平板电脑的销售量。自从Android发布以来，Android手机的激活量已经达到3亿台。谷歌Android主管安迪·罗宾（Andy Rubin）今天在其Google+ 网页上公布了该数据。和其他主要无线电运营商一样，谷歌也参加了此次世界移动大会（MWC）。",77,515);
$z[1][4]['name']="description";
$z[2]=Array("field","Android设备日激活量85万台 激活量破3亿",517,605);
$z[2][4]['name']="title";
$z[3]=Array("field","",607,646);
$z[3][4]['name']="writer";
$z[4]=Array("field","",648,687);
$z[4][4]['name']="source";
$z[5]=Array("field","",689,729);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",731,768);
$z[6][4]['name']="body";
$z[7]=Array("field","",770,815);
$z[7][4]['name']="download_url";
$z[8]=Array("field","",817,856);
$z[8][4]['name']="app_id";
$z[9]=Array("field","",858,897);
$z[9][4]['name']="litpic";

?>