<?php
$z[0]=Array("field","谷歌,Android应用商店,负责",0,74);
$z[0][4]['name']="keywords";
$z[1]=Array("field","在最近一周，有关Android Market的消息不绝于耳。最新的消息称，目前已经在Android团队工作4年半之久的埃里克·楚（Eric Chu)将不再担任Android应用商店的负责人职务，但仍留在谷歌从事其它工作。与此同时，Android数字内容主管兼谷歌音乐（Google Music）发布人杰米·罗森伯格（Jamie Rosenberg)将被赋予多项职责，包",76,524);
$z[1][4]['name']="description";
$z[2]=Array("field","谷歌Android应用商店负责人调任其他岗位",526,616);
$z[2][4]['name']="title";
$z[3]=Array("field","",618,657);
$z[3][4]['name']="writer";
$z[4]=Array("field","",659,698);
$z[4][4]['name']="source";
$z[5]=Array("field","",700,740);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",742,779);
$z[6][4]['name']="body";
$z[7]=Array("field","",781,826);
$z[7][4]['name']="download_url";
$z[8]=Array("field","",828,867);
$z[8][4]['name']="app_id";
$z[9]=Array("field","",869,908);
$z[9][4]['name']="litpic";

?>