<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>\"); ",15,169);
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",184,199);
$z[2]=Array("title","",215,229);
$z[3]=Array("pubdate","",289,335);
$z[3][4]['function']="GetDateTimeMK(@me)";
$z[4]=Array("click","",366,380);
$z[5]=Array("scores","",411,426);
$z[6]=Array("description","",469,489);

?>