{dede:field name='keywords'}Siri,Smart Voice,Vega S5{/dede:field}
{dede:field name='description'}在苹果Siri之后，Android的语音助理可谓是“组队”来袭，先是三星S Voice，接着是LG的Quick Voice，而据最新消息，韩国另一家手机厂商泛泰公司也已经推出了自家的语音助理应用——Smart Voice。{/dede:field}
{dede:field name='title'}Siri再遇对手 泛泰推语音助理Smart Voice{/dede:field}
{dede:field name='writer'}鹏哥哥{/dede:field}
{dede:field name='source'}安卓哥{/dede:field}
{dede:field name='pubdate'}2012-7-2 18:05:04{/dede:field}
{dede:field name='body'}<a href='http://www.apkge.com/group/phone' title='手机新闻'><img src='/Article/uploads/allimg/c120706/1341561341D040-24362.gif' align='right' alt='手机新闻'/></a>
                
                <p>
	在苹果Siri之后，Android的语音助理可谓是“组队”来袭，先是三星S Voice，接着是LG的Quick Voice，而据最新消息，韩国另一家手机厂商泛泰公司也已经推出了自家的语音助理应用——<strong>Smart Voice。</strong> 
</p>
<p>
	泛泰公司日前宣布，本月将在韩国本土推出<strong>一款5英寸的Android 4.0手机Vega S5</strong>，作为最大特色，该手机将内置泛泰自家的Smart Voice语音助理。
</p>
<p>
	硬件配置上，<strong>Vega S5采用720P的IPS LCD屏幕，配备高通S4处理器以及1300万像素主摄像头。</strong>该机将于7月4日展开预订，本月的晚些时候会正式出货。
</p>
<p>
	比较奇怪的是，号称5寸屏的Vega S5在机身尺寸上，无论是宽度还是高度都小于4.8寸的Galaxy S III（Galaxy S III尺寸：136.6 mm x 70.7 mm x 8.6 mm，Vega S5尺寸：134.8 mm x 68.8 mm x 9 mm），唯一可以解释的就是泛泰手机采用了更窄的边框设计（当然，不排除某一方的数据错误）。
</p>
<p style="text-align:center;">
	<a href="http://news.mydrivers.com/img/20120702/4805830a977441da87ceb119f1051a38.jpg" target="_blank"><img alt="Siri再逢敌手 泛泰推语音助理Smart Voice" src="/attached/images/20120702/20120702180412_8906.jpg" style="border-top-width:1px;border-right-width:1px;border-bottom-width:1px;border-left-width:1px;border-style:initial;border-color:initial;" /></a> 
</p>{/dede:field}
{dede:field name='download_url'}{/dede:field}
{dede:field name='app_id'}{/dede:field}
{dede:field name='litpic'}/Article/uploads/allimg/c120706/1341561341D040-24362_lit.gif{/dede:field}
