<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","",89,127);
$z[2][4]['name']="title";
$z[3]=Array("field","",129,168);
$z[3][4]['name']="writer";
$z[4]=Array("field","",170,209);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-7-4 12:23:05",211,268);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",270,307);
$z[6][4]['name']="body";
$z[7]=Array("field","",309,354);
$z[7][4]['name']="download_url";
$z[8]=Array("field","",356,395);
$z[8][4]['name']="app_id";
$z[9]=Array("field","/Article/uploads/allimg/c120706/13415615a333Z-3HT.png",397,489);
$z[9][4]['name']="litpic";

?>