<?php
$z[0]=Array("spaceurl","",145,163);
$z[1]=Array("face","",192,205);
$z[2]=Array("spaceurl","",246,264);
$z[3]=Array("uname","",283,297);
$z[4]=Array("spaceurl","",334,352);
$z[5]=Array("spaceurl","",405,423);
$z[6]=Array("spaceurl","",487,505);
$z[7]=Array("rankname","",622,640);
$z[8]=Array("jointime","",702,754);
$z[8][4]['function']="MyDate('Y-m-d H:m',@me)";
$z[9]=Array("logintime","",816,869);
$z[9][4]['function']="MyDate('Y-m-d H:m',@me)";

?>