<?php
$z[0]=Array("field","手机木马,疯狂“变脸”为",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","木马通过伪装实现“变脸”的行为并不稀奇，但“面具”高达近 150 种的手机木马却极为罕见。近期，一批名为“变脸”的手机木马家族在安卓平台异常活跃，中招用户手机往往会出现话费莫名被扣。根据 360 云安全中心监测数据，截至 2 月 15 日，该系列木马变种样本已接近 150 款，包括贪吃蛇、俄罗斯方",77,524);
$z[1][4]['name']="description";
$z[2]=Array("field","手机木马疯狂“变脸”为扣费 已感染近150个安卓应用",526,634);
$z[2][4]['name']="title";
$z[3]=Array("field","",636,675);
$z[3][4]['name']="writer";
$z[4]=Array("field","",677,716);
$z[4][4]['name']="source";
$z[5]=Array("field","",718,758);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",760,797);
$z[6][4]['name']="body";
$z[7]=Array("field","",799,844);
$z[7][4]['name']="download_url";
$z[8]=Array("field","",846,885);
$z[8][4]['name']="app_id";
$z[9]=Array("field","",887,926);
$z[9][4]['name']="litpic";

?>