{dede:field name='keywords'}Samsung,GT-B5330,QWERTY{/dede:field}
{dede:field name='description'}最近推出的手机大部份都是直板全触控的设计，大家可能会有点闷，甚至连 Blackberry 都开始不只推出 QWERTY 手机了；幸好在 Android 阵营我们找到这部 Samsung GT-B5330，虽然只是谍照，但直向屏幕搭配 QWERTY 键盘的设计总算有点新意。{/dede:field}
{dede:field name='title'}Samsung GT-B5330 谍照流出 屏幕搭配 QWERTY 键盘{/dede:field}
{dede:field name='writer'}鹏哥哥{/dede:field}
{dede:field name='source'}安卓哥{/dede:field}
{dede:field name='pubdate'}2012-7-3 16:33:05{/dede:field}
{dede:field name='body'}<a href='http://www.apkge.com/group/samsung' title='手机厂商 / 三星 / SAMSUNG'><img src='/Article/uploads/allimg/c120706/13415615FSY0-114c.gif' align='right' alt='手机厂商 / 三星 / SAMSUNG'/></a>
                
                <p>
	最近推出的手机大部份都是直板全触控的设计，大家可能会有点闷，甚至连&nbsp;Blackberry&nbsp;都开始不只推出 QWERTY 手机了；幸好在 Android 阵营我们找到这部 Samsung GT-B5330，虽然只是谍照，但直向屏幕搭配 QWERTY 键盘的设计总算有点新意。由 Sammy Hub 报导的信息，我们得知此机使用的是一片 QVGA 320 x 240 分辨率的屏幕，而处理器速度则是 850MHz；加上机背那个没有补光灯的镜头，我们就知道高端 QWERTY 手机的希望又落空了 -- 也许其经 Samsung 调整的&nbsp;Android 4.0&nbsp;系统，可以让我们好过一点吧？
</p>
<p style="text-align:center;">
	<img src="/Article/uploads/allimg/c120706/13415615V55L0-24914.jpg" /> 
</p>{/dede:field}
{dede:field name='download_url'}{/dede:field}
{dede:field name='app_id'}{/dede:field}
{dede:field name='litpic'}/Article/uploads/allimg/c120706/13415615FSY0-114c_lit.gif{/dede:field}
