<?php
$z[0]=Array("field","Samsung,GT-B5330,QWERTY",0,64);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最近推出的手机大部份都是直板全触控的设计，大家可能会有点闷，甚至连 Blackberry 都开始不只推出 QWERTY 手机了；幸好在 Android 阵营我们找到这部 Samsung GT-B5330，虽然只是谍照，但直向屏幕搭配 QWERTY 键盘的设计总算有点新意。",66,410);
$z[1][4]['name']="description";
$z[2]=Array("field","Samsung GT-B5330 谍照流出 屏幕搭配 QWERTY 键盘",412,506);
$z[2][4]['name']="title";
$z[3]=Array("field","鹏哥哥",508,556);
$z[3][4]['name']="writer";
$z[4]=Array("field","安卓哥",558,606);
$z[4][4]['name']="source";
$z[5]=Array("field","2012-7-3 16:33:05",608,665);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<a href='http://www.apkge.com/group/samsung' title='手机厂商 / 三星 / SAMSUNG'><img src='/Article/uploads/allimg/c120706/13415615FSY0-114c.gif' align='right' alt='手机厂商 / 三星 / SAMSUNG'/></a>\r\n                \r\n                <p>\r\n	最近推出的手机大部份都是直板全触控的设计，大家可能会有点闷，甚至连&nbsp;Blackberry&nbsp;都开始不只推出 QWERTY 手机了；幸好在 Android 阵营我们找到这部 Samsung GT-B5330，虽然只是谍照，但直向屏幕搭配 QWERTY 键盘的设计总算有点新意。由 Sammy Hub 报导的信息，我们得知此机使用的是一片 QVGA 320 x 240 分辨率的屏幕，而处理器速度则是 850MHz；加上机背那个没有补光灯的镜头，我们就知道高端 QWERTY 手机的希望又落空了 -- 也许其经 Samsung 调整的&nbsp;Android 4.0&nbsp;系统，可以让我们好过一点吧？\r\n</p>\r\n<p style=\"text-align:center;\">\r\n	<img src=\"/Article/uploads/allimg/c120706/13415615V55L0-24914.jpg\" /> \r\n</p>",667,1719);
$z[6][4]['name']="body";
$z[7]=Array("field","",1721,1766);
$z[7][4]['name']="download_url";
$z[8]=Array("field","",1768,1807);
$z[8][4]['name']="app_id";
$z[9]=Array("field","/Article/uploads/allimg/c120706/13415615FSY0-114c_lit.gif",1809,1905);
$z[9][4]['name']="litpic";

?>