{dede:noteinfo notename="采集测试" channelid="1" macthtype="string"
refurl="http://www.rzjiechu.com/html/guanyujiechu/jiechudongtai/list_7_1.html" sourcelang="gb2312" cosort="asc" isref="no" exptime="10" usemore="0" /}

{dede:listrule sourcetype="batch" rssurl="http://" regxurl="http://www.rzjiechu.com/html/guanyujiechu/jiechudongtai/list_7_(*).html"
startid="1" endid="2" addv="1" urlrule="area"
 musthas=".html" nothas="" listpic="1" usemore="0"}
    {dede:addurls}{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div id="jcliebiao">
<ul style="height:395px;">{/dede:areastart}
    {dede:areaend}</ul>
            <ul class="pagelist">{/dede:areaend}
{/dede:listrule}
