<?php
$z[0]=Array("noteinfo","",0,222);
$z[0][4]['notename']="采集测试";
$z[0][4]['channelid']="1";
$z[0][4]['macthtype']="string";
$z[0][4]['refurl']="http://www.rzjiechu.com/html/guanyujiechu/jiechudongtai/list_7_1.html";
$z[0][4]['sourcelang']="gb2312";
$z[0][4]['cosort']="asc";
$z[0][4]['isref']="no";
$z[0][4]['exptime']="10";
$z[0][4]['usemore']="0";
$z[1]=Array("listrule","\n    {dede:addurls}{/dede:addurls}\n    {dede:batchrule}{/dede:batchrule}\n    {dede:regxrule}{/dede:regxrule}\n    {dede:areastart}<div id=\"jcliebiao\">\r\n<ul style=\"height:395px;\">{/dede:areastart}\n    {dede:areaend}</ul>\r\n            <ul class=\"pagelist\">{/dede:areaend}\n",224,739);
$z[1][4]['sourcetype']="batch";
$z[1][4]['rssurl']="http://";
$z[1][4]['regxurl']="http://www.rzjiechu.com/html/guanyujiechu/jiechudongtai/list_7_(*).html";
$z[1][4]['startid']="1";
$z[1][4]['endid']="2";
$z[1][4]['addv']="1";
$z[1][4]['urlrule']="area";
$z[1][4]['musthas']=".html";
$z[1][4]['nothas']="";
$z[1][4]['listpic']="1";
$z[1][4]['usemore']="0";

?>