<?php
$z[0]=Array("field","",49,77);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",79,108);
$z[1][4]['name']="typename";
$z[2]=Array("field","",136,164);
$z[2][4]['name']="typeurl";
$z[3]=Array("arclist","\r\n\r\n				<div class=\"category_dis\">\r\n\r\n					<a href=\"[field:arcurl/]\" title=\"[field:title/]\" target=\"_blank\">[field:image/]</a><h4><a href=\"[field:arcurl/]\" target=\"_blank\" title=\"[field:title/]\">[field:title/]</a></h4><p>[field:info/]...</p>\r\n\r\n				</div>\r\n\r\n				",198,583);
$z[3][4]['row']="1";
$z[3][4]['orderby']="pubdate";
$z[3][4]['type']="image.";
$z[3][4]['imgwidth']="120";
$z[3][4]['imgheight']="95";
$z[3][4]['titlelen']="44";
$z[3][4]['infolen']="70";
$z[4]=Array("arclist","\r\n\r\n					<li><a href=\"[field:arcurl /]\" target=\"_blank\">[field:title /]</a></li>\r\n\r\n					",604,748);
$z[4][4]['titlelen']="45";
$z[4][4]['limit']="1,4";

?>