<?php
$z[0]=Array("field","HTC,4G新机Fireball,即将到来",0,74);
$z[0][4]['name']="keywords";
$z[1]=Array("field","之前曾有一款名为HTC Fireball的4G手机出现在Verizon公司的系统里面，日前有国外媒体报道称该机即将到来，而且将会换上新名字——HTC Droid Incredible 4G。Droid Incredible 4G将搭载1.2GHz双核处理器，配备1GB的RAM和8GB的内存，该机还采用一块AMOLED屏幕，带有800万像素主摄像头以及30万像素前置摄像头。",76,503);
$z[1][4]['name']="description";
$z[2]=Array("field","HTC 4G新机Fireball换名 即将到来",505,582);
$z[2][4]['name']="title";
$z[3]=Array("field","",584,623);
$z[3][4]['name']="writer";
$z[4]=Array("field","",625,664);
$z[4][4]['name']="source";
$z[5]=Array("field","",666,706);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",708,745);
$z[6][4]['name']="body";
$z[7]=Array("field","",747,792);
$z[7][4]['name']="download_url";
$z[8]=Array("field","",794,833);
$z[8][4]['name']="app_id";
$z[9]=Array("field","",835,874);
$z[9][4]['name']="litpic";

?>