<?php
$z[0]=Array("field","Android平板,GO Launcher HD Be",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","根据国外媒体报道，在我购入Galaxy Nexus之前，我一直都是GO Launcher EX的死忠。其实最开始的时候我并不愿意去尝试它，不过在我的一个好朋友的强力推荐下我试用了一整天，之后就再也离不开它了。现在我已经无法想象一台Android 4.0之前版本系统的手机如果不安装GO Launcher EX会有多难用。",74,496);
$z[1][4]['name']="description";
$z[2]=Array("field","进军Android平板 GO Launcher HD Beta版",498,578);
$z[2][4]['name']="title";
$z[3]=Array("field","",580,619);
$z[3][4]['name']="writer";
$z[4]=Array("field","",621,660);
$z[4][4]['name']="source";
$z[5]=Array("field","",662,702);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",704,741);
$z[6][4]['name']="body";
$z[7]=Array("field","",743,788);
$z[7][4]['name']="download_url";
$z[8]=Array("field","",790,829);
$z[8][4]['name']="app_id";
$z[9]=Array("field","",831,870);
$z[9][4]['name']="litpic";

?>