<?php
$z[0]=Array("field","北欧,HTC Sensation,启动Andr",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","位于北欧国家的HTC Sensation用户们最好尝试点击一下“Check update”按钮了，因为根据国外XDA论坛的消息，针对HTC Sensation的Android 4.0 Ice Cream Sandwich OTA升级已经开始了。",74,334);
$z[1][4]['name']="description";
$z[2]=Array("field","北欧HTC Sensation启动Android 4.0升级",336,416);
$z[2][4]['name']="title";
$z[3]=Array("field","",418,457);
$z[3][4]['name']="writer";
$z[4]=Array("field","",459,498);
$z[4][4]['name']="source";
$z[5]=Array("field","",500,540);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",542,579);
$z[6][4]['name']="body";
$z[7]=Array("field","",581,626);
$z[7][4]['name']="download_url";
$z[8]=Array("field","",628,667);
$z[8][4]['name']="app_id";
$z[9]=Array("field","",669,708);
$z[9][4]['name']="litpic";

?>