{dede:field name='keywords'}U.love,Android外形,iPhone应急{/dede:field}
{dede:field name='description'}U.love全球首款 Android外形移动电源，以可爱的Android机器人为灵感，摆脱了以往移动电源沉闷、乏味的设计模式，化身为一个Android精灵，大胆独特而又萌态十足。{/dede:field}
{dede:field name='title'}U.love全球首款Android外形iPhone应急电源上市{/dede:field}
{dede:field name='writer'}鹏哥哥{/dede:field}
{dede:field name='source'}安卓哥{/dede:field}
{dede:field name='pubdate'}2012-7-2 21:02:28{/dede:field}
{dede:field name='body'}<a href='http://www.apkge.com/group/peijian' title='手机配件'><img src='/Article/uploads/allimg/c120706/134156142F6110-95259.png' align='right' alt='手机配件'/></a>
                
                U.love全球首款 Android外形移动电源，以可爱的Android机器人为灵感，摆脱了以往移动电源沉闷、乏味的设计模式，化身为一个Android精灵，大胆独特而又萌态十足。<br />
<br />
<p style="text-align:center;">
	<img src="http://www.apkge.com/attached/images/20120702/20120702210022_8125.jpg" alt="严阵以待的Android外形移动电源" /> <img src="/Article/uploads/allimg/c120706/134156145O01P-11G91.jpg" alt="U.love全球首款Android外形iPhone应急电源上市" />&nbsp;
</p>
<p style="text-align:center;">
	严阵以待的Android外形移动电源
</p>
<br />
U.love Android外形移动电源，整体设计彰显品牌特质，细节之处体现人性关怀。外观上秉承了U.love品牌一贯的极简主义设计风格。一体式人性化设计，内置USB2.0输入口和苹果原装接口(或Micro USB接口)输出口，外出使用，无需携带任何数据线，即可满足自身的供电充电需求。<br />
<br />

	<img src="/Article/uploads/allimg/c120706/134156146339530-12R35.jpg" alt="内置苹果接口或Micro输出口和USB输入口" /> 


	内置苹果接口或Micro输出口和USB输入口

<br />
U.love Android外形移动电源，机身顶部Android小人两条俏皮的触须之间隐藏着一颗电量显示按键，只需轻轻一按，安置在Android腹部的LED灯就会发出光芒，当电量低于一半时LED灯为红色显示，当电量充足时，LED灯则为蓝色显示，通过它，你可以随时了解电源电量，让你在外出使用时更加从容无忧。<br />
<br />
而Android小人的两只小眼睛，则更会给你一个意料不到的惊喜。接通充电器后，它用红色的眼睛看着你，说明充电正在进行中，而当它用魅惑的蓝色看着你时，说明充电已完成。强大而又充满喜感的充电显示功能，在给用户带来惊喜的同时，也为用户带来更多便利。Android小人两只小脚内置防滑胶垫的设计。<br />
<br />

	<img src="http://www.apkge.com/attached/images/20120702/20120702210023_2031.jpg" alt="U.love全球首款Android外形移动电源" />


	U.love全球首款Android外形移动电源

<br />
U.love Android外形移动电源，有黑、白、绿、蓝、粉五种颜色可供选择。儒雅的白色，高贵而典雅，纯洁而迷人;稳健坚定的黑色，优雅大气;以及清新的绿、魅惑的蓝和可人的粉，每种色彩都自然而又不失时尚。此外，此款产品还分两种款式，一款内置苹果原装接头，可为iPhone、ipod等苹果产品充电;另一款内置Micro USB接口，则主要是为广大Android智能手机充电。<br />
<br />

	
		<img src="http://www.apkge.com/attached/images/20120702/20120702210023_2656.jpg" alt="新潮的外观，精巧的设计，丰富的色彩，宽广的兼容性以及强大的性能，足以满足不同特质消费人群的个性化需求，亦可为亲友间相互馈赠的时尚佳品。" /> 
	
新潮的外观，精巧的设计，丰富的色彩，宽广的兼容性以及强大的性能，足以满足不同特质消费人群的个性化需求，亦可为亲友间相互馈赠的时尚佳品。<br />
<br />
	
		<img src="/Article/uploads/allimg/c120706/13415614c21320-156429.jpg" alt="U.love全球首款Android外形iPhone应急电源上市" /> 
	
<br />
U.love作为苹果授权的配件制造商，多年来一直致力于给消费者提供轻松、时尚、新颖的配件产品。而U.love此款全球首次采用Android外形的移动电源，也是U.love品牌多年来一直坚持创新、敢为天下先的大气魄的完美见证。{/dede:field}
{dede:field name='download_url'}{/dede:field}
{dede:field name='app_id'}{/dede:field}
{dede:field name='litpic'}/Article/uploads/allimg/c120706/134156142F6110-95259_lit.png{/dede:field}
