{dede:field name='keywords'}360特供机,超级战舰,双核{/dede:field}
{dede:field name='description'}今天，360的又一款特供机揭开了面纱。家电巨头海尔与360将合作推出首款软硬兼防的超高配置智能手机，名字也很霸气——“超级战舰”。据介绍，“超级战舰”W910采用28纳米、1.5GHz双核CPU，4.5寸HD视网膜屏，1G RAM、8G ROM，是一款IP54级“防水、防尘、防刮”三防手机！{/dede:field}
{dede:field name='title'}360新款特供机售价1888元：1.5G双核CPU 4.5寸HD视网膜屏{/dede:field}
{dede:field name='writer'}鹏哥哥{/dede:field}
{dede:field name='source'}安卓哥{/dede:field}
{dede:field name='pubdate'}2012-7-3 16:51:10{/dede:field}
{dede:field name='body'}<a href='http://www.apkge.com/group/360' title='Qihoo / 奇虎 / 360'><img src='/Article/uploads/allimg/c120706/13415615a333Z-3HT.png' align='right' alt='Qihoo / 奇虎 / 360'/></a>
                
                今天，360的又一款特供机揭开了面纱。家电巨头海尔与360将合作推出首款软硬兼防的超高配置智能手机，名字也很霸气——“超级战舰”。
<p>
	据介绍，“超级战舰”W910采用28纳米、1.5GHz双核CPU，4.5寸HD视网膜屏，1G RAM、8G ROM，是一款IP54级“防水、防尘、防刮”三防手机！
</p>
<p style="text-align:center;">
	<img alt="360联合海尔推出特供机“超级战舰”" src="/Article/uploads/allimg/c120706/134156160Q1060-42Y6.jpg" style="border-top-width:1px;border-right-width:1px;border-bottom-width:1px;border-left-width:1px;border-style:initial;border-color:initial;" /> 
</p>
<p>
	<br />
</p>

	<img alt="360联合海尔推出特供机“超级战舰”" src="/Article/uploads/allimg/c120706/134156161363a0-5BB.png" style="border-top-width:1px;border-right-width:1px;border-bottom-width:1px;border-left-width:1px;" /> 


	<a href="http://e.weibo.com/360tegong?ref=http%3A%2F%2Fs.weibo.com%2Fweibo%2F360%25E7%2594%25A8%25E6%2588%25B7%25E7%2589%25B9%25E4%25BE%259B%25E6%259C%25BA%3F%26topnav%3D1%26topsug%3D1" target="_blank"></a><a href="http://e.weibo.com/360tegong?ref=http%3A%2F%2Fs.weibo.com%2Fweibo%2F360%25E7%2594%25A8%25E6%2588%25B7%25E7%2589%25B9%25E4%25BE%259B%25E6%259C%25BA%3F%26topnav%3D1%26topsug%3D1" target="_blank">360特供机微博</a> 

<p>
	<br />
</p>
<p>
	Update：
</p>
<p>
	今天下午360联合海尔正式发布其第三款特供手机——“海尔超级旗舰”W910，配备4.5寸视网膜屏幕和高通1.5G双核处理器，售价1888元，将于7月下旬上市。
</p>
<p>
	“海尔超级旗舰”W910配备了28纳米制程的高通8260A双核1.5G处理器和美国康宁公司的大金刚二代防刮蹭玻璃，采用130万像素和800万像素前后两个摄像头，支持1080P高清摄录、1G RAM内存、8G ROM存储、以及4.5寸视网膜屏幕，分辨率达到了720*1280，像素密度为326像素/英寸。
</p>
<p>
	真机图赏：
</p>
<p>
	<a href="http://news.mydrivers.com/picture/233146/233146_1.html" target="_blank"><img alt="360新款特供机1888元：1.5G双核CPU/视网膜屏" src="/attached/images/20120703/20120703164745_7812.jpg" style="border-top-width:1px;border-right-width:1px;border-bottom-width:1px;border-left-width:1px;border-style:initial;border-color:initial;" /></a> 
</p>
<p>
	<a href="http://news.mydrivers.com/picture/233146/233146_2.html" target="_blank"><img alt="360新款特供机1888元：1.5G双核CPU/视网膜屏" src="/attached/images/20120703/20120703164746_1718.jpg" style="border-top-width:1px;border-right-width:1px;border-bottom-width:1px;border-left-width:1px;border-style:initial;border-color:initial;" /></a> 
</p>
<p>
	<a href="http://news.mydrivers.com/picture/233146/233146_3.html" target="_blank"><img alt="360新款特供机1888元：1.5G双核CPU/视网膜屏" src="/attached/images/20120703/20120703164746_3750.jpg" style="border-top-width:1px;border-right-width:1px;border-bottom-width:1px;border-left-width:1px;border-style:initial;border-color:initial;" /></a> 
</p>
<p>
	<a href="http://news.mydrivers.com/picture/233146/233146_4.html" target="_blank"><img alt="360新款特供机1888元：1.5G双核CPU/视网膜屏" src="/attached/images/20120703/20120703164746_5000.jpg" style="border-top-width:1px;border-right-width:1px;border-bottom-width:1px;border-left-width:1px;border-style:initial;border-color:initial;" /></a> 
</p>
<p>
	<a href="http://news.mydrivers.com/picture/233146/233146_5.html" target="_blank"><img alt="360新款特供机1888元：1.5G双核CPU/视网膜屏" src="/attached/images/20120703/20120703164747_3437.jpg" style="border-top-width:1px;border-right-width:1px;border-bottom-width:1px;border-left-width:1px;border-style:initial;border-color:initial;" /></a> 
</p>
<p>
	<br />
</p>
<p align="center" style="color:#333333;font-family:Verdana， 宋体;font-size:14px;line-height:24px;white-space:normal;background-color:#FFFFFF;">
	<a href="http://news.mydrivers.com/picture/233146/233146_6.html" target="_blank" style="color:#000000;text-decoration:none;"><img alt="360新款特供机1888元：1.5G双核CPU/视网膜屏" src="/attached/images/20120703/20120703164747_4687.jpg" style="border-top-width:1px;border-right-width:1px;border-bottom-width:1px;border-left-width:1px;border-style:initial;border-color:initial;" /></a> 
</p>
<p align="center" style="color:#333333;font-family:Verdana， 宋体;font-size:14px;line-height:24px;white-space:normal;background-color:#FFFFFF;">
	<a href="http://news.mydrivers.com/picture/233146/233146_7.html" target="_blank" style="color:#000000;text-decoration:none;"><img alt="360新款特供机1888元：1.5G双核CPU/视网膜屏" src="/attached/images/20120703/20120703164748_4375.jpg" style="border-top-width:1px;border-right-width:1px;border-bottom-width:1px;border-left-width:1px;border-style:initial;border-color:initial;" /></a> 
</p>
<p align="center" style="color:#333333;font-family:Verdana， 宋体;font-size:14px;line-height:24px;white-space:normal;background-color:#FFFFFF;">
	<a href="http://news.mydrivers.com/picture/233146/233146_8.html" target="_blank" style="color:#000000;text-decoration:none;"><img alt="360新款特供机1888元：1.5G双核CPU/视网膜屏" src="/attached/images/20120703/20120703164749_5468.jpg" style="border-top-width:1px;border-right-width:1px;border-bottom-width:1px;border-left-width:1px;border-style:initial;border-color:initial;" /></a> 
</p>
<p align="center" style="color:#333333;font-family:Verdana， 宋体;font-size:14px;line-height:24px;white-space:normal;background-color:#FFFFFF;">
	<a href="http://news.mydrivers.com/picture/233146/233146_9.html" target="_blank" style="color:#000000;text-decoration:none;"><img alt="360新款特供机1888元：1.5G双核CPU/视网膜屏" src="/attached/images/20120703/20120703164750_7343.jpg" style="border-top-width:1px;border-right-width:1px;border-bottom-width:1px;border-left-width:1px;border-style:initial;border-color:initial;" /></a> 
</p>
<p align="center" style="color:#333333;font-family:Verdana， 宋体;font-size:14px;line-height:24px;white-space:normal;background-color:#FFFFFF;">
	<a href="http://news.mydrivers.com/picture/233146/233146_10.html" target="_blank" style="color:#000000;text-decoration:none;"><img alt="360新款特供机1888元：1.5G双核CPU/视网膜屏" src="/attached/images/20120703/20120703164751_0781.jpg" style="border-top-width:1px;border-right-width:1px;border-bottom-width:1px;border-left-width:1px;border-style:initial;border-color:initial;" /></a> 
</p>
<p align="center" style="color:#333333;font-family:Verdana， 宋体;font-size:14px;line-height:24px;white-space:normal;background-color:#FFFFFF;">
	<a href="http://news.mydrivers.com/picture/233146/233146_11.html" target="_blank" style="color:#000000;text-decoration:none;"><img alt="360新款特供机1888元：1.5G双核CPU/视网膜屏" src="/attached/images/20120703/20120703164751_4218.jpg" style="border-top-width:1px;border-right-width:1px;border-bottom-width:1px;border-left-width:1px;border-style:initial;border-color:initial;" /></a> 
</p>
<p align="center" style="color:#333333;font-family:Verdana， 宋体;font-size:14px;line-height:24px;white-space:normal;background-color:#FFFFFF;">
	<a href="http://news.mydrivers.com/picture/233146/233146_12.html" target="_blank" style="color:#000000;text-decoration:none;"><img alt="360新款特供机1888元：1.5G双核CPU/视网膜屏" src="/attached/images/20120703/20120703164752_2812.jpg" style="border-top-width:1px;border-right-width:1px;border-bottom-width:1px;border-left-width:1px;border-style:initial;border-color:initial;" /></a> 
</p>
<p align="center" style="color:#333333;font-family:Verdana， 宋体;font-size:14px;line-height:24px;white-space:normal;background-color:#FFFFFF;">
	<a href="http://news.mydrivers.com/picture/233146/233146_13.html" target="_blank" style="color:#000000;text-decoration:none;"><img alt="360新款特供机1888元：1.5G双核CPU/视网膜屏" src="/attached/images/20120703/20120703164752_5781.jpg" style="border-top-width:1px;border-right-width:1px;border-bottom-width:1px;border-left-width:1px;border-style:initial;border-color:initial;" /></a> 
</p>
<p align="center" style="color:#333333;font-family:Verdana， 宋体;font-size:14px;line-height:24px;white-space:normal;background-color:#FFFFFF;">
	<a href="http://news.mydrivers.com/picture/233146/233146_14.html" target="_blank" style="color:#000000;text-decoration:none;"><img alt="360新款特供机1888元：1.5G双核CPU/视网膜屏" src="/attached/images/20120703/20120703164753_4218.jpg" style="border-top-width:1px;border-right-width:1px;border-bottom-width:1px;border-left-width:1px;border-style:initial;border-color:initial;" /></a> 
</p>
<p align="center" style="color:#333333;font-family:Verdana， 宋体;font-size:14px;line-height:24px;white-space:normal;background-color:#FFFFFF;">
	<a href="http://news.mydrivers.com/picture/233146/233146_15.html" target="_blank" style="color:#000000;text-decoration:none;"><img alt="360新款特供机1888元：1.5G双核CPU/视网膜屏" src="/attached/images/20120703/20120703164754_2500.jpg" style="border-top-width:1px;border-right-width:1px;border-bottom-width:1px;border-left-width:1px;border-style:initial;border-color:initial;" /></a> 
</p>
<p align="center" style="color:#333333;font-family:Verdana， 宋体;font-size:14px;line-height:24px;white-space:normal;background-color:#FFFFFF;">
	<a href="http://news.mydrivers.com/picture/233146/233146_16.html" target="_blank" style="color:#000000;text-decoration:none;"><img alt="360新款特供机1888元：1.5G双核CPU/视网膜屏" src="/attached/images/20120703/20120703164755_1093.jpg" style="border-top-width:1px;border-right-width:1px;border-bottom-width:1px;border-left-width:1px;border-style:initial;border-color:initial;" /></a> 
</p>
<p align="center" style="color:#333333;font-family:Verdana， 宋体;font-size:14px;line-height:24px;white-space:normal;background-color:#FFFFFF;">
	<a href="http://news.mydrivers.com/picture/233146/233146_17.html" target="_blank" style="color:#000000;text-decoration:none;"><img alt="360新款特供机1888元：1.5G双核CPU/视网膜屏" src="/attached/images/20120703/20120703164756_0625.jpg" style="border-top-width:1px;border-right-width:1px;border-bottom-width:1px;border-left-width:1px;border-style:initial;border-color:initial;" /></a> 
</p>
<p align="center" style="color:#333333;font-family:Verdana， 宋体;font-size:14px;line-height:24px;white-space:normal;background-color:#FFFFFF;">
	<a href="http://news.mydrivers.com/picture/233146/233146_18.html" target="_blank" style="color:#000000;text-decoration:none;"><img alt="360新款特供机1888元：1.5G双核CPU/视网膜屏" src="/attached/images/20120703/20120703164757_1875.jpg" style="border-top-width:1px;border-right-width:1px;border-bottom-width:1px;border-left-width:1px;border-style:initial;border-color:initial;" /></a> 
</p>
<p align="center" style="color:#333333;font-family:Verdana， 宋体;font-size:14px;line-height:24px;white-space:normal;background-color:#FFFFFF;">
	<a href="http://news.mydrivers.com/picture/233146/233146_19.html" target="_blank" style="color:#000000;text-decoration:none;"><img alt="360新款特供机1888元：1.5G双核CPU/视网膜屏" src="/attached/images/20120703/20120703164758_1093.jpg" style="border-top-width:1px;border-right-width:1px;border-bottom-width:1px;border-left-width:1px;border-style:initial;border-color:initial;" /></a> 
</p>
<p align="center" style="color:#333333;font-family:Verdana， 宋体;font-size:14px;line-height:24px;white-space:normal;background-color:#FFFFFF;">
	<a href="http://news.mydrivers.com/picture/233146/233146_20.html" target="_blank" style="color:#FF0000;text-decoration:none;"><img alt="360新款特供机1888元：1.5G双核CPU/视网膜屏" src="/attached/images/20120703/20120703164759_0156.jpg" style="border-top-width:1px;border-right-width:1px;border-bottom-width:1px;border-left-width:1px;border-style:initial;border-color:initial;" /></a> 
</p>
<p align="center" style="color:#333333;font-family:Verdana， 宋体;font-size:14px;line-height:24px;white-space:normal;background-color:#FFFFFF;">
	<a href="http://news.mydrivers.com/picture/233146/233146_21.html" target="_blank" style="color:#000000;text-decoration:none;"><img alt="360新款特供机1888元：1.5G双核CPU/视网膜屏" src="/attached/images/20120703/20120703164759_3906.jpg" style="border-top-width:1px;border-right-width:1px;border-bottom-width:1px;border-left-width:1px;border-style:initial;border-color:initial;" /></a> 
</p>
<p>
	<br />
</p>{/dede:field}
{dede:field name='download_url'}{/dede:field}
{dede:field name='app_id'}{/dede:field}
{dede:field name='litpic'}/Article/uploads/allimg/c120706/13415615a333Z-3HT_lit.png{/dede:field}
