{dede:field name='keywords'}华为,4G多模上网猫{/dede:field}
{dede:field name='description'}7月9日消息，日本电信运营商Emobile再度联手华为推出全球首款LTE Category 4多模Mobile Wi-Fi产品E5776，该款产品是目前全球LTE网络下载速度最快的终端，最大下载速度可以达到150Mbps，且最多可同时支持10个带Wi-Fi接入的设备接入。不仅如此，E5776还是全球第一款支持Wi-Fi 2×2的Mobile Wi-Fi终端，相比市面上同类型其他{/dede:field}
{dede:field name='title'}[图]华为推4G多模上网猫 速率150M支持10设备接入{/dede:field}
{dede:field name='writer'}鹏哥哥{/dede:field}
{dede:field name='source'}安卓哥{/dede:field}
{dede:field name='pubdate'}2012-7-9 12:20:41{/dede:field}
{dede:field name='body'}<p>
	7月9日消息，<span style="font-weight:bold;">日本电信运营商Emobile再度联手华为推出全球首款LTE Category 4多模Mobile Wi-Fi产品E5776，该款产品是目前全球LTE网络下载速度最快的终端，最大下载速度可以达到150Mbps，且最多可同时支持10个带Wi-Fi接入的设备接入。</span>不仅如此，E5776还是全球第一款支持Wi-Fi 2×2的Mobile Wi-Fi终端，相比市面上同类型其他产品，其Wi-Fi速度得到了翻倍的提升。
</p>
<p>
	
		<img alt="华为推4G多模上网猫 速率150M支持10设备介入" src="/Article/uploads/allimg/c120709/1341QAB06250-1X58.jpg" /> 
	
	<p style="font-size:10pt;font-family:宋体;text-align:center;">
		华为首款LTE Category 4多模Mobile Wi-Fi产品E5776
	</p>
	<p style="text-indent:2em;">
		华为E5776采用横屏设计，外观圆润，方便用户操作而且更容易携带。支持10个带Wi-Fi接入的设备接入LTE。后续E5776还将支持Mobile Control和SD share功能，通过手机或屏类终端的Mobile Control控制端软件，用户可以方便、快速地查看E5776的各种状态并设置各种参数；SD share功能则可以让用户通过Wi-Fi和朋友一起自在分享SD卡里的各种图片、文档、音乐和视频等资料。
	</p>
	<p style="text-indent:2em;">
		E5776内置最大可支持10个小时工作时间的大容量电池，可以同步满足市面上95%以上电池供电设备通过Wi-Fi连接上网，包括iPad、各种智能手机和<span class="a-tips-Article-QQ">笔记本</span>电脑等。在Cat 4 150Mbps下载速度的LTE网络下，一部1GB的高清电影，只需要不到1分钟时间就可以完成下载。
	</p>
	<p style="text-indent:2em;">
		作为全球LTE网络及终端产业链的重要领导者，华为终端一直在LTE技术研发方面处于领先，并始终引领全球LTE的商用进程。此外，华为是多个LTE标准化组织的成员，公司员工在多个LTE组织中担任着重要职务。
	</p>
	<p style="text-indent:2em;">
		继业界首款LTE DD800单模CPE终端B390，全球首款LTE/UMTS/GSM多模数据卡E398，全球首款LTE TDD多模数据卡E392，全球首款TDD/FDD多模CPE终端B593，全球最长工作时间Mobile Wi-Fi E589等多款领先产品之后，此次华为发布的全球首款LTE Cat 4 Mobile Wi-Fi多模终端E5776，又将进一步推动LTE的产业进程。
	</p>{/dede:field}
{dede:field name='download_url'}{/dede:field}
{dede:field name='app_id'}{/dede:field}
{dede:field name='litpic'}/Article/uploads/allimg/c120709/1341QAB06250-1X58_lit.jpg{/dede:field}
