<?php
$z[0]=Array("field","华硕,Android 5.0更新",0,65);
$z[0][4]['name']="keywords";
$z[1]=Array("field","在本届世界移动通信大会上，各种新型智能手机设备以及与之相关的新技术层出不穷令人眼花缭乱。但人们似乎还是更热衷于讨论那些有关谷歌新一代安卓操作系统的话题。近日，华硕公司就出面证实称，谷歌将会在年内推出下一代安卓操作系统，并将其命名为“Android 5.0 Jelly Bean（安卓5.0果冻豆）”。",67,511);
$z[1][4]['name']="description";
$z[2]=Array("field","华硕有望率先推出Android 5.0更新",513,592);
$z[2][4]['name']="title";
$z[3]=Array("field","",594,633);
$z[3][4]['name']="writer";
$z[4]=Array("field","",635,674);
$z[4][4]['name']="source";
$z[5]=Array("field","",676,716);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",718,755);
$z[6][4]['name']="body";
$z[7]=Array("field","",757,802);
$z[7][4]['name']="download_url";
$z[8]=Array("field","",804,843);
$z[8][4]['name']="app_id";
$z[9]=Array("field","",845,884);
$z[9][4]['name']="litpic";

?>