{dede:field name='keywords'}三星,Galaxy S Blaze,android新机{/dede:field}
{dede:field name='description'}三星今天宣布其最新智能机三星Galaxy S Blaze 4G在美国T-Mobile上市销售，它工作在该运营商的HSPA+频段下，采用4.5吋高清屏幕，并且搭载了双核1.5GHz处理器。该机的外形为三星Galaxy系列经典设计，出货时间3月28日，合约价149.99美元。{/dede:field}
{dede:field name='title'}三星 Galaxy S Blaze 4G售149.99美元{/dede:field}
{dede:field name='writer'}鹏哥哥{/dede:field}
{dede:field name='source'}安卓哥{/dede:field}
{dede:field name='pubdate'}2012-3-22 20:45:49{/dede:field}
{dede:field name='body'}<a href='http://www.apkge.com/group/samsung' title='手机厂商 / 三星 / SAMSUNG'><img src='/Article/uploads/allimg/c120706/13415615FSY0-114c.gif' align='right' alt='手机厂商 / 三星 / SAMSUNG'/></a>
                
                <p style="padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px;margin-top:0px;margin-bottom:20px;text-indent:28px;font-family:宋体;font-size:14px;line-height:22px;white-space:normal;background-color:#FFFFFF;">
	三星今天宣布其最新智能机三星Galaxy S Blaze 4G在美国T-Mobile上市销售，它工作在该运营商的HSPA+频段下，采用4.5吋高清屏幕，并且搭载了双核1.5GHz处理器。该机的外形为三星Galaxy系列经典设计，出货时间3月28日，合约价149.99美元。
</p>
<p align="center" style="padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px;margin-top:0px;margin-bottom:20px;text-indent:28px;font-family:宋体;font-size:14px;line-height:22px;white-space:normal;background-color:#FFFFFF;">
	<img title="Android 新机 三星Galaxy S Blaze 4G售价149.99美元" alt="Android 新机 三星Galaxy S Blaze 4G售价149.99美元" src="http://www.apkge.com/attached/images/20120322/20120322204417_4233.jpg" border="0" style="padding-top:2px;padding-right:2px;padding-bottom:2px;padding-left:2px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;border-top-width:1px;border-right-width:1px;border-bottom-width:1px;border-left-width:1px;border-style:initial;border-color:initial;" /> 
</p>
<p style="padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px;margin-top:0px;margin-bottom:20px;text-indent:28px;font-family:宋体;font-size:14px;line-height:22px;white-space:normal;background-color:#FFFFFF;">
	三星GALAXY S Blaze 4G采用的是4.5吋高清屏幕，并且搭载了双核1.5GHz处理器，支持T-Mobile的LTE 4G网络。同时该机将会采用三星GALAXY系列经典设计，内置Android2.3系统。
</p>{/dede:field}
{dede:field name='download_url'}{/dede:field}
{dede:field name='app_id'}{/dede:field}
{dede:field name='litpic'}/Article/uploads/allimg/c120706/13415615FSY0-114c_lit.gif{/dede:field}
