<?php
$z[0]=Array("field","传谷歌Android5.0系统将抢在",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","据悉，Android 5.0操作系统的产品代号是 Jelly Bean（果冻豆）。谷歌表示Android 5.0将进一步针对平板电脑进行优化，而谷歌将会针对厂商推销Android 5.0与Chrome OS的整合方案，以推动双操作系统设计。另外Android 5.0也支持与Windows 8合体，厂商们也可以选择将Android 5.0与Windows 8系统整合在同一产品上，用户可以在两个",77,526);
$z[1][4]['name']="description";
$z[2]=Array("field","传谷歌Android5.0系统将抢在苹果iOS6之前发布",528,622);
$z[2][4]['name']="title";
$z[3]=Array("field","",624,663);
$z[3][4]['name']="writer";
$z[4]=Array("field","",665,704);
$z[4][4]['name']="source";
$z[5]=Array("field","",706,746);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",748,785);
$z[6][4]['name']="body";
$z[7]=Array("field","",787,832);
$z[7][4]['name']="download_url";
$z[8]=Array("field","",834,873);
$z[8][4]['name']="app_id";
$z[9]=Array("field","",875,914);
$z[9][4]['name']="litpic";

?>