<?php
$z[0]=Array("noteinfo","",0,200);
$z[0][4]['notename']="安卓哥采集到新闻";
$z[0][4]['channelid']="1";
$z[0][4]['macthtype']="string";
$z[0][4]['refurl']="http://www.apkge.com/page1.html";
$z[0][4]['sourcelang']="utf-8";
$z[0][4]['cosort']="asc";
$z[0][4]['isref']="no";
$z[0][4]['exptime']="5";
$z[0][4]['usemore']="0";
$z[1]=Array("listrule","\n    {dede:addurls}{/dede:addurls}\n    {dede:batchrule}http://www.apkge.com/page1.html\r\nhttp://www.apkge.com/page2.html{/dede:batchrule}\n    {dede:regxrule}{/dede:regxrule}\n    {dede:areastart}<div class=\"bg0\">{/dede:areastart}\n    {dede:areaend}<div id=\"pager\" >{/dede:areaend}\n",201,688);
$z[1][4]['sourcetype']="batch";
$z[1][4]['rssurl']="http://";
$z[1][4]['regxurl']="http://www.apkge.com/page(*).html";
$z[1][4]['startid']="1";
$z[1][4]['endid']="2";
$z[1][4]['addv']="1";
$z[1][4]['urlrule']="area";
$z[1][4]['musthas']=".html";
$z[1][4]['nothas']="";
$z[1][4]['listpic']="1";
$z[1][4]['usemore']="0";

?>