<?php
$z[0]=Array("noteinfo","",2,163);
$z[0][4]['notename']="³±Á÷½ÚÅÄ";
$z[0][4]['channelid']="1";
$z[0][4]['macthtype']="string";
$z[0][4]['refurl']="http://";
$z[0][4]['sourcelang']="gb2312";
$z[0][4]['cosort']="asc";
$z[0][4]['isref']="no";
$z[0][4]['exptime']="10";
$z[0][4]['usemore']="0";
$z[1]=Array("listrule","\r\n	{dede:addurls}http://woman.39.net/nxsh/gjgw/jtcl/{/dede:addurls}\r\n	{dede:batchrule}{/dede:batchrule}\r\n	{dede:regxrule}{/dede:regxrule}\r\n	{dede:areastart}<div class=\"newslist\">\r\n{/dede:areastart}\r\n	{dede:areaend}<div class=\"page\">\r\n{/dede:areaend}\r\n",165,650);
$z[1][4]['sourcetype']="batch";
$z[1][4]['rssurl']="http://";
$z[1][4]['regxurl']="http://woman.39.net/nxsh/gjgw/jtcl/index_(*).html";
$z[1][4]['startid']="2";
$z[1][4]['endid']="3";
$z[1][4]['addv']="1";
$z[1][4]['urlrule']="area";
$z[1][4]['musthas']="woman.39.net/";
$z[1][4]['nothas']="";
$z[1][4]['listpic']="0";
$z[1][4]['usemore']="0";

?>