
{dede:noteinfo notename="³±Á÷½ÚÅÄ" channelid="1" macthtype="string"
	refurl="http://" sourcelang="gb2312" cosort="asc"
  isref="no" exptime="10" usemore="0" /}
{dede:listrule sourcetype="batch" rssurl="http://" regxurl="http://woman.39.net/nxsh/gjgw/jtcl/index_(*).html"
startid="2" endid="3" addv="1" urlrule="area" musthas="woman.39.net/"
 nothas="" listpic="0" usemore="0"}
	{dede:addurls}http://woman.39.net/nxsh/gjgw/jtcl/{/dede:addurls}
	{dede:batchrule}{/dede:batchrule}
	{dede:regxrule}{/dede:regxrule}
	{dede:areastart}<div class="newslist">
{/dede:areastart}
	{dede:areaend}<div class="page">
{/dede:areaend}
{/dede:listrule}

