{dede:field name='keywords'}鳄鱼爱洗澡,Android用户{/dede:field}
{dede:field name='description'}《鳄鱼爱洗澡》是一款风靡全球的手机游戏，目前已衍生出了很多版本，如鳄鱼爱洗澡中文节日版、鳄鱼爱洗澡新增63关、鳄鱼小顽皮爱洗澡等。热门游戏一直是病毒乐意寄生的地方，近日腾讯移动安全实验室就截获了一款“嚣张”的Android病毒反动联盟2（a.fraud.eyu），该病毒将恶意代码注入十余个版本的《{/dede:field}
{dede:field name='title'}病毒入侵鳄鱼爱洗澡 300万Android用户遭殃{/dede:field}
{dede:field name='writer'}鹏哥哥{/dede:field}
{dede:field name='source'}安卓哥{/dede:field}
{dede:field name='pubdate'}2012-7-2 18:06:58{/dede:field}
{dede:field name='body'}<a href='http://www.apkge.com/group/warning' title='安全播报'><img src='/Article/uploads/allimg/c120706/13415613TET0-BH2.png' align='right' alt='安全播报'/></a>
                
                <p>
	《鳄鱼爱洗澡》是一款风靡全球的手机游戏，目前已衍生出了很多版本，如鳄鱼爱洗澡中文节日版、鳄鱼爱洗澡新增63关、鳄鱼小顽皮爱洗澡等。热门游戏一直是病毒乐意寄生的地方，近日腾讯移动安全实验室就截获了一款“嚣张”的Android病毒反动联盟2（a.fraud.eyu），该病毒将恶意代码注入十余个版本的《鳄鱼爱洗澡》游戏。
</p>
<p>
	&nbsp;&nbsp;此前也发现了《鳄鱼爱洗澡》的部分版本被注入恶意推广代码，会骚扰用户，在手机系统通知栏弹广告。但反动联盟2病毒行经更恶劣，一旦激活会攻击指定的手机安全软件，还会在通知栏弹广告，私自下载应用，耗费用户流量。据腾讯移动安全实验室保守估计，此次受“反动联盟2”病毒感染的Android用户数接近300万。目前，腾讯手机管家已支持精准查杀该病毒，建议从官网（<a href="http://msm.qq.com/">http://msm.qq.com/</a>）下载安装，并开启全盘扫描，围剿反动联盟2病毒。
</p>
<p>
	&nbsp;&nbsp;病毒特征：
</p>
<p>
	&nbsp;&nbsp;“反动联盟2”病毒通过恶意代码注入热门游戏《鳄鱼爱洗澡》的多个版本，激活后会攻击手机安全软件，私自弹出广告，偷偷下载应用。
</p>
<p>
	&nbsp;&nbsp;特征一、攻击手机安全软件。该病毒一旦启动，会在软件界面弹出“安全提示”框，告诉用户“系统检测到你的手机安装了**（手机安全软件），该软件权限过大，会私自获取聊天记录……，建议立即删除”，用户一点击“马上删除”，即跳转到软件卸载界面。就这样，用户会误把手机里的安全软件卸载掉，使手机裸机下运行，风险大增。
</p>
<p style="text-align:center;">
	<img alt="" src="http://www.apkge.com/attached/images/20120702/20120702180634_8906.jpg" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px;outline-width:0px;outline-style:initial;outline-color:initial;vertical-align:baseline;width:390px;height:321px;" /> 
</p>
<p style="text-align:center;">
	（图1：病毒引导用户卸载手机上的安全软件）
</p>
<p>
	&nbsp;&nbsp;特征二、弹广告骚扰用户。该病毒会在手机系统通知栏弹广告，点击后立即下载软件且无法手动取消，从而造成用户手机流量消耗，带来严重的经济损失。
</p>
<p>
	&nbsp;&nbsp;病毒截图：
</p>
<p style="text-align:center;">
	<img alt="" height="366" src="/Article/uploads/allimg/c120706/13415614052O0-U245.jpg" width="460" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px;outline-width:0px;outline-style:initial;outline-color:initial;vertical-align:baseline;width:394px;height:350px;" /> 
</p>
<p style="text-align:center;">
	（图2：手机管家查杀反动联盟2病毒）
</p>
<p>
	&nbsp;&nbsp;专家支招：
</p>
<p>
	&nbsp;&nbsp;目前，腾讯手机管家已经实现对“反动联盟2”病毒的精准查杀，用户应尽快从腾讯手机管家官方网站<a href="http://msm.qq.com/">http://msm.qq.com/</a>下载安装，同时升级病毒库至最新，然后开启全盘扫描，即可完成查杀。
</p>
<p>
	&nbsp;&nbsp;此外，由于“反动联盟2”病毒感染的《鳄鱼爱洗澡》系列Android游戏仍然潜伏在部分电子市场、论坛、WWW\WAP站点供用户下载，专家特别提醒Android手机用户在下载应用时务必提高警惕。建议用户到腾讯应用中心或通过腾讯手机管家自带的“软件游戏”功能进行下载，或利用QQ电脑管家的手机管理功能，直接在电脑免费下载上万款手机软件，这些应用都经过腾讯手机管家的安全认证，可以有效保证应用的安全。
</p>{/dede:field}
{dede:field name='download_url'}{/dede:field}
{dede:field name='app_id'}{/dede:field}
{dede:field name='litpic'}/Article/uploads/allimg/c120706/13415613TET0-BH2_lit.png{/dede:field}
