<?php
$z[0]=Array("global","",202,229);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",231,257);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",308,335);
$z[2][4]['name']="phpurl";
$z[3]=Array("tag","<a href='[field:link/]' target=\"_blank\">[field:tag /]</a>",876,985);
$z[3][4]['row']="4";
$z[3][4]['getall']="1";
$z[3][4]['sort']="rand";
$z[4]=Array("global","",1063,1090);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("channel","<a href='[field:typeurl/]' [field:rel/]>[field:typename/]</a>",1188,1367);
$z[5][4]['type']="top";
$z[5][4]['row']="10";
$z[5][4]['currentstyle']="<a class='cut' href='~typelink~' ~rel~>~typename~</a>";
$z[6]=Array("global","",1610,1635);
$z[6][4]['name']="cfg_cmsurl";

?>