<?php
$z[0]=Array("include","",0,38);
$z[0][4]['filename']="headmin.htm";
$z[1]=Array("global","",112,139);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("global","",141,167);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",218,245);
$z[3][4]['name']="phpurl";
$z[4]=Array("tag","<a href='[field:link/]' target=\"_blank\">[field:tag /]</a>",740,849);
$z[4][4]['row']="5";
$z[4][4]['getall']="1";
$z[4][4]['sort']="rand";
$z[5]=Array("global","",924,949);
$z[5][4]['name']="cfg_cmsurl";
$z[6]=Array("channel","|<a href='[field:typeurl/]' [field:rel/]>[field:typename/]</a>",1123,1304);
$z[6][4]['type']="top";
$z[6][4]['row']="10";
$z[6][4]['currentstyle']="|<a class='cut' href='~typelink~' ~rel~>~typename~</a>";

?>