<?php
$z[0]=Array("global","",30,59);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("field","",101,130);
$z[1][4]['name']="typename";
$z[2]=Array("field","",145,174);
$z[2][4]['name']="typelink";
$z[3]=Array("field","",195,247);
$z[3][4]['name']="title";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("field","",309,337);
$z[4][4]['name']="powerby";
$z[5]=Array("field","",364,395);
$z[5][4]['name']="adminemail";
$z[6]=Array("rssitem","\n<item>\n    <title><![CDATA[[field:title/]]]></title>\n    <link>[field:fullurl/]</link>\n    <description><![CDATA[[field:description function='html2text(@me)'/]]]></description>\n    <pubDate>[field:stime/]</pubDate>\n    <category>[field:typename/]</category>\n    <author>[field:writer/]</author>\n    <comments>[field:source/]</comments>\n</item>\n",408,782);

?>