<?php
$z[0]=Array("global","",233,261);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("field","",273,292);
$z[1][4]['name']="title";
$z[2]=Array("global","",293,319);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",359,388);
$z[3][4]['name']="keywords";
$z[4]=Array("field","",427,485);
$z[4][4]['name']="description";
$z[4][4]['function']="html2text(@me)";
$z[5]=Array("global","",502,534);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",663,688);
$z[6][4]['name']="cfg_cmsurl";
$z[7]=Array("include","",753,788);
$z[7][4]['filename']="head.htm";
$z[8]=Array("tag","\n            <a href='[field:link/]' class='tagc[field:highlight /]'>[field:tag /]</a>\n            ",999,1139);
$z[8][4]['row']="60";
$z[8][4]['sort']="new";
$z[9]=Array("tag","\n            <a href='[field:link/]' class='tagc[field:highlight /]'>[field:tag /]</a>\n            ",1284,1426);
$z[9][4]['row']="60";
$z[9][4]['sort']="month";
$z[10]=Array("tag","\n            <a href='[field:link/]' class='tagc[field:highlight /]'>[field:tag /]</a>\n            ",1565,1707);
$z[10][4]['row']="100";
$z[10][4]['sort']="rand";
$z[11]=Array("include","",1743,1780);
$z[11][4]['filename']="footer.htm";

?>