<?php
$z[0]=Array("global","",242,270);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("field","",297,316);
$z[1][4]['name']="title";
$z[2]=Array("global","",317,343);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",386,415);
$z[3][4]['name']="keywords";
$z[4]=Array("field","",457,515);
$z[4][4]['name']="description";
$z[4][4]['function']="html2text(@me)";
$z[5]=Array("global","",568,593);
$z[5][4]['name']="cfg_cmsurl";
$z[6]=Array("include","",1103,1139);
$z[6][4]['filename']="head2.htm";
$z[7]=Array("tag"," <a href='[field:link/]' class='tagc'>[field:tag /]</a> ",1217,1315);
$z[7][4]['row']="100";
$z[7][4]['sort']="new";
$z[8]=Array("tag"," <a href='[field:link/]' class='tagc'>[field:tag /]</a> ",1380,1480);
$z[8][4]['row']="100";
$z[8][4]['sort']="month";
$z[9]=Array("tag"," <a href='[field:link/]' class='tagc'>[field:tag /]</a> ",1548,1647);
$z[9][4]['row']="100";
$z[9][4]['sort']="rand";
$z[10]=Array("include","",1668,1708);
$z[10][4]['filename']="footer2.htm";

?>