<?php
$z[0]=Array("global","",236,264);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("field","",289,308);
$z[1][4]['name']="title";
$z[2]=Array("global","",309,335);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",376,405);
$z[3][4]['name']="keywords";
$z[4]=Array("field","",445,503);
$z[4][4]['name']="description";
$z[4][4]['function']="html2text(@me)";
$z[5]=Array("include","",600,636);
$z[5][4]['filename']="head2.htm";
$z[6]=Array("tag"," <a href='[field:link/]' class='tagc'>[field:tag /]</a> ",706,804);
$z[6][4]['row']="100";
$z[6][4]['sort']="new";
$z[7]=Array("tag"," <a href='[field:link/]' class='tagc'>[field:tag /]</a> ",863,963);
$z[7][4]['row']="100";
$z[7][4]['sort']="month";
$z[8]=Array("tag"," <a href='[field:link/]' class='tagc'>[field:tag /]</a> ",1025,1124);
$z[8][4]['row']="100";
$z[8][4]['sort']="rand";
$z[9]=Array("include","",1141,1181);
$z[9][4]['filename']="footer2.htm";

?>