<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('4917', '/Article/uploads/allimg/120820/24-120R02216430-L.jpg');
$maNum = 1;
$myaddons[$maNum] = array('4918', '/Article/uploads/allimg/120820/24-120R0222011Y1.jpg');
$maNum = 2;
$myaddons[$maNum] = array('4919', '/Article/uploads/allimg/120820/24-120R022225Y94.jpg');
$maNum = 3;
$myaddons[$maNum] = array('4920', '/Article/uploads/allimg/120820/24-120R0222605935.png');
$maNum = 4;
$myaddons[$maNum] = array('4921', '/Article/uploads/allimg/120820/24-120R022264G94.png');
$maNum = 5;
$myaddons[$maNum] = array('4922', '/Article/uploads/allimg/120820/24-120R0222I5543.png');
$maNum = 6;
$myaddons[$maNum] = array('4923', '/Article/uploads/allimg/120820/24-120R0222PEA.png');
$maNum = 7;
