<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('1969', '/Article/uploads/allimg/120506/3-1205061050400-L.png');
$maNum = 1;
$myaddons[$maNum] = array('1970', '/Article/uploads/allimg/120506/3-12050610513Kb.png');
$maNum = 2;
$myaddons[$maNum] = array('1971', '/Article/uploads/allimg/120506/3-120506105313292.png');
$maNum = 3;
$myaddons[$maNum] = array('1972', '/Article/uploads/allimg/120506/3-12050610533W10.png');
$maNum = 4;
