<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('3707', '/Article/uploads/allimg/120614/13-1206141K33S02.jpg');
$maNum = 1;
$myaddons[$maNum] = array('3708', '/Article/uploads/allimg/120614/13-1206141K3512c.jpg');
$maNum = 2;
$myaddons[$maNum] = array('3709', '/Article/uploads/allimg/120614/13-1206141K403953.jpg');
$maNum = 3;
$myaddons[$maNum] = array('3710', '/Article/uploads/allimg/120614/13-1206141K424220.jpg');
$maNum = 4;
$myaddons[$maNum] = array('3711', '/Article/uploads/allimg/120614/13-1206141K445H0.jpg');
$maNum = 5;
