<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('1147', '/Article/uploads/allimg/120406/3-1204061R2570-L.png');
$maNum = 1;
$myaddons[$maNum] = array('1148', '/Article/uploads/allimg/120406/3-1204061R35J20.png');
$maNum = 2;
$myaddons[$maNum] = array('1149', '/Article/uploads/allimg/120406/3-1204061R644630.jpg');
$maNum = 3;
$myaddons[$maNum] = array('1150', '/Article/uploads/allimg/120406/3-1204061RHI60.jpg');
$maNum = 4;
$myaddons[$maNum] = array('1151', '/Article/uploads/allimg/120406/3-1204061RK5N5.jpg');
$maNum = 5;
$myaddons[$maNum] = array('1152', '/Article/uploads/allimg/120406/3-1204061RS6125.jpg');
$maNum = 6;
