<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('1763', '/Article/uploads/allimg/120426/2-1204261410550-L.png');
$maNum = 1;
$myaddons[$maNum] = array('1764', '/Article/uploads/allimg/120426/2-120426141119351.png');
$maNum = 2;
$myaddons[$maNum] = array('1765', '/Article/uploads/allimg/120426/2-120426141132505.png');
$maNum = 3;
$myaddons[$maNum] = array('1766', '/Article/uploads/allimg/120426/2-1204261413044D.png');
$maNum = 4;
$myaddons[$maNum] = array('1767', '/Article/uploads/allimg/120426/2-12042614134U05.png');
$maNum = 5;
$myaddons[$maNum] = array('1768', '/Article/uploads/allimg/120426/2-12042614152SB.png');
$maNum = 6;
