<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('2180', '/Article/uploads/allimg/120509/2-1205091404440-L.png');
$maNum = 1;
$myaddons[$maNum] = array('2181', '/Article/uploads/allimg/120509/2-12050914050Nc.png');
$maNum = 2;
$myaddons[$maNum] = array('2182', '/Article/uploads/allimg/120509/2-120509140531410.png');
$maNum = 3;
$myaddons[$maNum] = array('2183', '/Article/uploads/allimg/120509/2-120509140550G7.png');
$maNum = 4;
$myaddons[$maNum] = array('2185', '/Article/uploads/allimg/120509/2-120509140JB47.png');
$maNum = 5;
$myaddons[$maNum] = array('2187', '/Article/uploads/allimg/120509/2-120509140T92N.png');
$maNum = 6;
