<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('4355', '/Article/uploads/allimg/120720/18-120H01612500-L.png');
$maNum = 1;
$myaddons[$maNum] = array('4356', '/Article/uploads/allimg/120720/18-120H0161322632.png');
$maNum = 2;
$myaddons[$maNum] = array('4357', '/Article/uploads/allimg/120720/18-120H0161523622.gif');
$maNum = 3;
$myaddons[$maNum] = array('4358', '/Article/uploads/allimg/120720/18-120H0161623635.jpg');
$maNum = 4;
$myaddons[$maNum] = array('4359', '/Article/uploads/allimg/120720/18-120H0161G1b3.jpg');
$maNum = 5;
$myaddons[$maNum] = array('4360', '/Article/uploads/allimg/120720/18-120H0161J6339.jpg');
$maNum = 6;
$myaddons[$maNum] = array('4361', '/Article/uploads/allimg/120720/18-120H0161T5616.jpg');
$maNum = 7;
