<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('2389', '/Article/uploads/allimg/120511/2-120511150J60-L.png');
$maNum = 1;
$myaddons[$maNum] = array('2390', '/Article/uploads/allimg/120511/2-120511150Q2A6.png');
$maNum = 2;
$myaddons[$maNum] = array('2391', '/Article/uploads/allimg/120511/2-120511150S5109.png');
$maNum = 3;
$myaddons[$maNum] = array('2392', '/Article/uploads/allimg/120511/2-120511150U34A.jpg');
$maNum = 4;
$myaddons[$maNum] = array('2394', '/Article/uploads/allimg/120511/2-1205111509455Q.png');
$maNum = 5;
$myaddons[$maNum] = array('2396', '/Article/uploads/allimg/120511/2-120511151043313.png');
$maNum = 6;
$myaddons[$maNum] = array('2399', '/Article/uploads/allimg/120511/2-120511151136460.png');
$maNum = 7;
